Repository ebean-orm/ebean, pull requests merged in 2018-04, with the labels that each got.

#1358 Fix Maven links in README
  README.md
Labels: documentation

#1361 Inheritance - Add support for @DiscriminatorValue to be optional
  src/main/java/io/ebeaninternal/server/deploy/InheritInfo.java
  src/main/java/io/ebeaninternal/server/deploy/parse/DeployInherit.java
  src/main/java/io/ebeaninternal/server/deploy/parse/DeployInheritInfo.java
Labels: enhancement

#1366 FIX: load all props from cache when inheritance is involved
  src/main/java/io/ebeaninternal/server/cache/CachedBeanDataToBean.java
  src/test/java/org/tests/cache/TestCacheManyToOne.java
  src/test/java/org/tests/model/basic/OCachedInhChildA.java
  src/test/java/org/tests/model/basic/OCachedInhChildB.java
  src/test/java/org/tests/model/basic/OCachedInhRoot.java
Labels: bug
