Repository ebean-orm/ebean, pull requests merged in 2018-06, with the labels that each got.

#1410 IOUtils is no longer used, using java 1.7 StandardCharsets makes Enco…
  src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonMap.java
  src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonNode.java
  src/main/java/io/ebeaninternal/server/type/SimpleAesEncryptor.java
  src/main/java/io/ebeaninternal/server/util/Md5.java
  src/main/java/io/ebeaninternal/util/EncodeUtil.java
  src/main/java/io/ebeaninternal/util/IOUtils.java
Labels: refactor

#1428 ENH: Use java.time.Clock for @WhenModified and @WhenCreated and allow it to be Replaceable for testing
  src/main/java/io/ebean/config/ServerConfig.java
  src/main/java/io/ebeaninternal/server/core/PersistRequestBean.java
  src/test/java/io/ebean/ExtendedServerTest.java
Labels: enhancement

#1435 Migration enum drop check constraints
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/MySqlDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl.java
  src/test/java/io/ebeaninternal/dbmigration/DbMigrationTest.java
  src/test/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdlTest.java
  src/test/java/misc/migration/v1_0/EEnum.java
  src/test/java/misc/migration/v1_1/EEnum.java
  src/test/java/misc/migration/v1_2/EEnum.java
  src/test/resources/dbmigration/migrationtest/db2/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/db2/1.1.sql
  src/test/resources/dbmigration/migrationtest/db2/1.3.sql
  src/test/resources/dbmigration/migrationtest/h2/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/h2/1.1.sql
  src/test/resources/dbmigration/migrationtest/h2/1.3.sql
  src/test/resources/dbmigration/migrationtest/hsqldb/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/hsqldb/1.1.sql
  src/test/resources/dbmigration/migrationtest/hsqldb/1.3.sql
  src/test/resources/dbmigration/migrationtest/model/1.0__initial.model.xml
  src/test/resources/dbmigration/migrationtest/model/1.1.model.xml
  src/test/resources/dbmigration/migrationtest/model/1.3.model.xml
  src/test/resources/dbmigration/migrationtest/mysql/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/mysql/1.3.sql
  src/test/resources/dbmigration/migrationtest/oracle/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/oracle/1.1.sql
  src/test/resources/dbmigration/migrationtest/oracle/1.3.sql
  src/test/resources/dbmigration/migrationtest/postgres/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/postgres/1.1.sql
  src/test/resources/dbmigration/migrationtest/postgres/1.3.sql
  src/test/resources/dbmigration/migrationtest/sqlite/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/sqlite/1.1.sql
  src/test/resources/dbmigration/migrationtest/sqlite/1.3.sql
  src/test/resources/dbmigration/migrationtest/sqlserver17/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/sqlserver17/1.1.sql
  src/test/resources/dbmigration/migrationtest/sqlserver17/1.3.sql
Labels: bug
