Repository ebean-orm/ebean, pull requests merged in 2018-11, with the labels that each got.

#1534 Code cleanup
  src/main/java/io/ebean/EbeanServer.java
  src/main/java/io/ebean/MergeOptionsBuilder.java
  src/main/java/io/ebean/Model.java
  src/main/java/io/ebean/config/BeanNotEnhancedException.java
  src/main/java/io/ebean/config/BeanNotRegisteredException.java
  src/main/java/io/ebeaninternal/api/SpiDtoQuery.java
  src/main/java/io/ebeaninternal/api/SpiTransaction.java
  src/main/java/io/ebeaninternal/api/SpiTransactionProxy.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdl.java
  src/main/java/io/ebeaninternal/dbmigration/model/MTable.java
  src/main/java/io/ebeaninternal/server/cache/DefaultServerQueryCache.java
  src/main/java/io/ebeaninternal/server/cluster/ClusterManager.java
  src/main/java/io/ebeaninternal/server/core/AbstractSqlQueryRequest.java
  src/main/java/io/ebeaninternal/server/core/DefaultSqlUpdate.java
  src/main/java/io/ebeaninternal/server/deploy/BaseCollectionHelp.java
  src/main/java/io/ebeaninternal/server/deploy/BeanCollectionHelp.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorElementEmbedded.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorElementScalar.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
  src/main/java/io/ebeaninternal/server/deploy/BeanEmbeddedMetaFactory.java
  src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssoc.java
  src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocMany.java
  src/main/java/io/ebeaninternal/server/deploy/ElementEntityBean.java
  src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  src/main/java/io/ebeaninternal/server/persist/ExeCallableSql.java
  src/main/java/io/ebeaninternal/server/persist/MergeNodeAssocManyToMany.java
  src/main/java/io/ebeaninternal/server/persist/MergeNodeAssocOne.java
  src/main/java/io/ebeaninternal/server/persist/MergeNodeAssocOneToMany.java
  src/main/java/io/ebeaninternal/server/query/DefaultOrmQueryEngine.java
  src/main/java/io/ebeaninternal/server/query/SqlTreeNodeManyRoot.java
  src/main/java/io/ebeaninternal/server/querydefn/DefaultDtoQuery.java
  src/main/java/io/ebeaninternal/server/transaction/BeanPersistIdMap.java
  src/main/java/io/ebeaninternal/server/transaction/ImplicitReadOnlyTransaction.java
  src/main/java/io/ebeaninternal/server/transaction/NoTransaction.java
  src/test/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl_AlterColumnTest.java
  src/test/java/io/ebeaninternal/server/grammer/EqlParserTest.java
  src/test/java/io/ebeaninternal/server/type/TypeReflectHelperTest.java
  src/test/java/org/MainMemoryLeak.java
  src/test/java/org/tests/changelog/TestChangeLog.java
  src/test/java/org/tests/inheritance/cache/TestInheritanceRefCache.java
  src/test/java/org/tests/model/basic/ResetBasicData.java
  src/test/java/org/tests/model/elementcollection/TestElementCollectionBasicMap.java
  src/test/java/org/tests/model/elementcollection/TestElementCollectionEmbeddedListCache.java
  src/test/java/org/tests/model/uuidsibling/USibChild.java
  src/test/java/org/tests/model/uuidsibling/USibChildSibling.java
  src/test/java/org/tests/model/uuidsibling/USibParent.java
  src/test/java/org/tests/o2m/jointable/TestOneToManyJoinTable.java
  src/test/java/org/tests/query/other/TestFindWhereUsingEnumerated.java
  src/test/java/org/tests/text/csv/TestCsvReaderWithCallback.java
Labels: refactor

#1531 Transform extra-ddl.xml files when running in ddl mode (no migration)
  src/main/java/io/ebeaninternal/dbmigration/DdlGenerator.java
  src/main/java/io/ebeaninternal/dbmigration/PlaceholderBuilder.java
  src/main/java/io/ebeaninternal/dbmigration/ScriptTransform.java
Labels: bug

#1527 FIX: improved support for @DbForeignKey(noConstraint = true)
  src/main/java/io/ebean/bean/EntityBeanIntercept.java
  src/main/java/io/ebeaninternal/api/LoadBeanRequest.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  src/main/java/io/ebeaninternal/server/query/STreePropertyAssocOne.java
  src/main/java/io/ebeaninternal/server/query/STreeType.java
  src/main/java/io/ebeaninternal/server/query/SqlTreeBuilder.java
  src/main/java/io/ebeaninternal/server/query/SqlTreeNodeBean.java
  src/test/java/org/tests/model/nofk/EFile2NoFk.java
  src/test/java/org/tests/model/nofk/EFileNoFk.java
  src/test/java/org/tests/model/nofk/EUserNoFk.java
  src/test/java/org/tests/model/nofk/EUserNoFkSoftDel.java
  src/test/java/org/tests/model/nofk/Test2NoFk.java
  src/test/java/org/tests/model/nofk/TestNoFk.java
Labels: bug

#1535 FIX: use outer join on "is null" check
  src/main/java/io/ebeaninternal/server/expression/NullExpression.java
  src/test/java/org/tests/query/TestOuterJoin.java
Labels: bug

#1537 Add Java 8 Time API support for BasicTypeConverter
  src/main/java/io/ebeaninternal/server/core/BasicTypeConverter.java
Labels: bug

#1538 Add some sanity checks when creating sort comparators
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  src/main/java/io/ebeaninternal/server/el/ElComparatorNoop.java
  src/main/java/io/ebeaninternal/server/el/ElComparatorProperty.java
  src/main/java/io/ebeaninternal/server/el/ElPropertyChain.java
Labels: enhancement

#1540 FIX for the limit query
  src/main/java/io/ebean/config/dbplatform/LimitOffsetSqlLimiter.java
  src/main/java/io/ebean/config/dbplatform/db2/Db2SqlLimiter.java
  src/main/java/io/ebean/config/dbplatform/hana/HanaSqlLimiter.java
  src/test/java/org/tests/basic/TestLimitQuery.java
  src/test/java/org/tests/query/TestAddOrderByWithFirstRowsMaxRows.java
Labels: bug

#1541 Fix test data
  src/test/java/org/tests/model/basic/ResetBasicData.java
  src/test/java/org/tests/types/TestPeriodType.java
Labels: refactor

#1539 FIX: Pairs must not be modified by query
  src/main/java/io/ebean/Pairs.java
  src/main/java/io/ebeaninternal/api/NaturalKeyQueryData.java
  src/main/java/io/ebeaninternal/server/expression/InExpression.java
  src/main/java/io/ebeaninternal/server/expression/InPairsExpression.java
  src/test/java/org/tests/model/basic/cache/TestCacheViaComplexNaturalKey3.java
Labels: bug

#1550 NEW: ExpressionPath provides access to property and elName
  src/main/java/io/ebean/plugin/ExpressionPath.java
  src/main/java/io/ebeaninternal/server/deploy/BeanFkeyProperty.java
  src/main/java/io/ebeaninternal/server/deploy/BeanProperty.java
  src/main/java/io/ebeaninternal/server/el/ElPropertyChain.java
Labels: enhancement

#1551 new comparison method Ine (caseInsensitive notEquals)
  src/main/java/io/ebean/ExpressionFactory.java
  src/main/java/io/ebean/ExpressionList.java
  src/main/java/io/ebeaninternal/server/expression/CaseInsensitiveEqualExpression.java
  src/main/java/io/ebeaninternal/server/expression/DefaultExpressionFactory.java
  src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  src/main/java/io/ebeaninternal/server/expression/DocQueryContext.java
  src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  src/main/java/io/ebeaninternal/server/grammer/EqlAdapter.java
  src/main/java/io/ebeaninternal/server/grammer/EqlAdapterHelper.java
  src/main/java/io/ebeaninternal/server/grammer/EqlOperator.java
  src/main/java/io/ebeaninternal/server/grammer/OperatorMapping.java
  src/main/java/io/ebeaninternal/server/grammer/antlr/EQL.tokens
  src/main/java/io/ebeaninternal/server/grammer/antlr/EQLBaseListener.java
  src/main/java/io/ebeaninternal/server/grammer/antlr/EQLLexer.java
  src/main/java/io/ebeaninternal/server/grammer/antlr/EQLLexer.tokens
  src/main/java/io/ebeaninternal/server/grammer/antlr/EQLListener.java
  src/main/java/io/ebeaninternal/server/grammer/antlr/EQLParser.java
  src/test/java/io/ebeaninternal/server/expression/CaseInsensitiveEqualExpressionTest.java
  src/test/java/io/ebeaninternal/server/expression/DefaultExpressionFactoryTest.java
  src/test/java/io/ebeaninternal/server/grammer/EqlParserTest.java
  src/test/java/org/tests/query/TestQueryFilterCaseInsensitive.java
  src/test/resources/EQL.g4
Labels: enhancement
