Repository ebean-orm/ebean, pull requests merged in 2018-10, with the labels that each got.

#1514 Add support for JacksonAnnotations at bean-properties
  src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanDescriptor.java
  src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanProperty.java
  src/main/java/io/ebeaninternal/server/deploy/parse/DeployUtil.java
  src/main/java/io/ebeaninternal/server/type/DefaultTypeManager.java
  src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonObjectMapper.java
  src/main/java/io/ebeaninternal/server/type/TypeManager.java
  src/test/java/org/tests/json/TestDbJson_Jackson.java
  src/test/java/org/tests/json/TestDbJson_Jackson2.java
  src/test/java/org/tests/model/json/BasicJacksonType.java
  src/test/java/org/tests/model/json/EBasicJsonJackson.java
  src/test/java/org/tests/model/json/EBasicJsonJackson2.java
  src/test/java/org/tests/model/json/LongJacksonType.java
  src/test/java/org/tests/model/json/StringJacksonType.java
Labels: enhancement

#1520 Javadoc Fix closing h3 tag in Transaction. no code change!
  src/main/java/io/ebean/Transaction.java
Labels: documentation

#1523 #1519 - Memory leak when using @Cache(enableQueryCache=true)
  src/main/java/io/ebeaninternal/api/TransactionEvent.java
  src/main/java/io/ebeaninternal/api/TransactionEventBeans.java
  src/main/java/io/ebeaninternal/server/core/PersistRequestBean.java
  src/main/java/io/ebeaninternal/server/deploy/BeanCollectionUtil.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorCacheHelp.java
  src/main/java/io/ebeaninternal/server/persist/DefaultPersister.java
  src/main/java/io/ebeaninternal/server/transaction/JdbcTransaction.java
  src/main/java/io/ebeaninternal/server/transaction/PostCommitProcessing.java
  src/main/java/io/ebeaninternal/server/transaction/TransactionManager.java
  src/test/java/io/ebean/config/PlatformNoGeneratedKeysTest.java
  src/test/java/org/MainMemoryLeak.java
  src/test/resources/ebean.properties
  src/test/resources/logback-test.xml
Labels: bug
