Repository ebean-orm/ebean, pull requests merged in 2018-08, with the labels that each got.

#1465 Add support for Postgres range partition DDL plus refactor xsd definitions that had got out of sync
  pom.xml
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PostgresDdl.java
  src/main/java/io/ebeaninternal/dbmigration/migration/AddColumn.java
  src/main/java/io/ebeaninternal/dbmigration/migration/AddHistoryTable.java
  src/main/java/io/ebeaninternal/dbmigration/migration/AddTableComment.java
  src/main/java/io/ebeaninternal/dbmigration/migration/AddUniqueConstraint.java
  src/main/java/io/ebeaninternal/dbmigration/migration/AlterColumn.java
  src/main/java/io/ebeaninternal/dbmigration/migration/AlterForeignKey.java
  src/main/java/io/ebeaninternal/dbmigration/migration/AlterHistoryTable.java
  src/main/java/io/ebeaninternal/dbmigration/migration/Apply.java
  src/main/java/io/ebeaninternal/dbmigration/migration/ChangeSet.java
  src/main/java/io/ebeaninternal/dbmigration/migration/ChangeSetType.java
  src/main/java/io/ebeaninternal/dbmigration/migration/Column.java
  src/main/java/io/ebeaninternal/dbmigration/migration/Configuration.java
  src/main/java/io/ebeaninternal/dbmigration/migration/CreateIndex.java
  src/main/java/io/ebeaninternal/dbmigration/migration/CreateTable.java
  src/main/java/io/ebeaninternal/dbmigration/migration/DdlScript.java
  src/main/java/io/ebeaninternal/dbmigration/migration/DefaultTablespace.java
  src/main/java/io/ebeaninternal/dbmigration/migration/DropColumn.java
  src/main/java/io/ebeaninternal/dbmigration/migration/DropHistoryTable.java
  src/main/java/io/ebeaninternal/dbmigration/migration/DropIndex.java
  src/main/java/io/ebeaninternal/dbmigration/migration/DropTable.java
  src/main/java/io/ebeaninternal/dbmigration/migration/ForeignKey.java
  src/main/java/io/ebeaninternal/dbmigration/migration/IdentityType.java
  src/main/java/io/ebeaninternal/dbmigration/migration/Migration.java
  src/main/java/io/ebeaninternal/dbmigration/migration/ObjectFactory.java
  src/main/java/io/ebeaninternal/dbmigration/migration/RenameColumn.java
  src/main/java/io/ebeaninternal/dbmigration/migration/RenameTable.java
  src/main/java/io/ebeaninternal/dbmigration/migration/Rollback.java
  src/main/java/io/ebeaninternal/dbmigration/migration/Sql.java
  src/main/java/io/ebeaninternal/dbmigration/migration/UniqueConstraint.java
  src/main/java/io/ebeaninternal/dbmigration/model/MCompoundUniqueConstraint.java
  src/main/java/io/ebeaninternal/dbmigration/model/MTable.java
  src/main/java/io/ebeaninternal/dbmigration/model/build/ModelBuildBeanVisitor.java
  src/main/java/io/ebeaninternal/dbmigration/model/build/ModelBuildPropertyVisitor.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  src/main/java/io/ebeaninternal/server/deploy/PartitionMeta.java
  src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanDescriptor.java
  src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationClass.java
  src/main/java/io/ebeaninternal/server/query/SqlTreeBuilder.java
  src/main/resources/ebean-dbmigration-1.0.xsd
  src/main/resources/ebean-extraddl-1.0.xsd
  src/test/resources/dbmigration/migrationtest/model/1.1.model.xml
  src/test/resources/dbmigration/migrationtest/model/1.3.model.xml
Labels: enhancement, refactor

#1469 #1468 - ENH: Add built-in DDL generation for Postgres table partitioning (by day, week, month and year)
  src/main/java/io/ebean/config/dbplatform/DatabasePlatform.java
  src/main/java/io/ebean/config/dbplatform/postgres/PostgresPlatform.java
  src/main/java/io/ebean/dbmigration/DbMigration.java
  src/main/java/io/ebeaninternal/dbmigration/DdlGenerator.java
  src/main/java/io/ebeaninternal/dbmigration/DefaultDbMigration.java
  src/main/java/io/ebeaninternal/dbmigration/model/CurrentModel.java
  src/main/java/io/ebeaninternal/dbmigration/model/MTable.java
  src/main/java/io/ebeaninternal/dbmigration/model/ModelContainer.java
  src/main/java/io/ebeaninternal/extraddl/model/ExtraDdlXmlReader.java
  src/main/resources/io/ebeaninternal/dbmigration/builtin-extra-ddl-partitioning.xml
Labels: enhancement

#1467 Let enum arrays be saved as integers or strings
  src/main/java/io/ebeaninternal/server/type/ArrayElementConverter.java
  src/main/java/io/ebeaninternal/server/type/ScalarTypeArrayList.java
  src/main/java/io/ebeaninternal/server/type/ScalarTypeArraySet.java
  src/test/java/org/tests/model/array/EArrayBean.java
  src/test/java/org/tests/model/array/IntEnum.java
  src/test/java/org/tests/model/array/TestDbArray_basic.java
  src/test/java/org/tests/model/array/VarcharEnum.java
Labels: enhancement

#1473 Fix for error with multiple uses of enum with integer storage type
  src/main/java/io/ebeaninternal/server/type/DefaultTypeManager.java
  src/test/java/org/tests/model/array/EArrayBean.java
Labels: bug
