Repository ebean-orm/ebean, pull requests merged in 2019-02, with the labels that each got.

#1637 build on jdk11
  pom.xml
  src/test/java/io/ebeaninternal/server/type/ScalarTypeInstantTest.java
  src/test/java/io/ebeaninternal/server/type/ScalarTypeLocalDateTimeTest.java
  src/test/java/io/ebeaninternal/server/type/ScalarTypeOffsetDateTimeTest.java
  src/test/java/io/ebeaninternal/server/type/ScalarTypeZonedDateTimeTest.java
Labels: refactor

#1635 Fixed missing EBEAN_PROPS_FILE loading
  src/main/java/io/ebean/config/properties/Loader.java
Labels: bug

#1638 FIX: When saving multiple m2m beans, only last m2m wins (Regression due #1630)
  src/main/java/io/ebeaninternal/server/core/PersistRequestBean.java
  src/main/java/io/ebeaninternal/server/persist/SaveManyBeans.java
  src/test/java/org/tests/sp/TestManyToManySaveTwice.java
  src/test/java/org/tests/sp/model/car/Car.java
  src/test/java/org/tests/sp/model/car/Door.java
Labels: bug

#1639 FIX: Proper sort of migration versions (possible regression due #1577)
  src/main/java/io/ebeaninternal/dbmigration/LastMigration.java
Labels: bug

#1641 #1640 - For Postgres support mapping InetAddress to INET db column
  pom.xml
  src/main/java/io/ebean/config/PlatformConfig.java
  src/main/java/io/ebean/config/dbplatform/DbPlatformTypeMapping.java
  src/main/java/io/ebean/config/dbplatform/DbType.java
  src/main/java/io/ebean/config/dbplatform/ExtraDbTypes.java
  src/main/java/io/ebean/config/dbplatform/postgres/PostgresPlatform.java
  src/main/java/io/ebeaninternal/server/type/ConvertInetAddresses.java
  src/main/java/io/ebeaninternal/server/type/DefaultTypeManager.java
  src/main/java/io/ebeaninternal/server/type/PostgresHelper.java
  src/main/java/io/ebeaninternal/server/type/ScalarTypeCdir.java
  src/main/java/io/ebeaninternal/server/type/ScalarTypeInet.java
  src/main/java/io/ebeaninternal/server/type/ScalarTypeInetAddressPostgres.java
  src/test/java/io/ebeaninternal/server/type/ConvertInetAddressTest.java
  src/test/java/org/tests/basic/type/TestInetAddressType.java
  src/test/java/org/tests/model/basic/EWithInetAddr.java
Labels: enhancement
