Repository ebean-orm/ebean, pull requests merged in 2019-01, with the labels that each got.

#1592 SqlServer queryplan captured in transaction & fix of possible NPE
  src/main/java/io/ebeaninternal/server/query/CQueryBindCapture.java
  src/main/java/io/ebeaninternal/server/query/QueryPlanLoggerSqlServer.java
Labels: bug

#1597 Refactor: replaced system-property "ebean.ignoreExtraDdl" with serverConfig flag
  src/main/java/io/ebean/config/ServerConfig.java
  src/main/java/io/ebeaninternal/dbmigration/DdlGenerator.java
  src/test/java/io/ebean/EbeanServerFactory_ServerConfigStart_Test.java
  src/test/java/io/ebean/event/BeanFindControllerTest.java
  src/test/java/io/ebean/event/BeanPersistControllerTest.java
  src/test/java/io/ebean/event/BeanPostLoadTest.java
  src/test/java/io/ebeaninternal/dbmigration/model/build/ModelBuild_compoundKeyTest.java
  src/test/java/io/ebeaninternal/dbmigration/model/build/ModelBuild_explicitSequencesTest.java
  src/test/java/io/ebeaninternal/server/deploy/BeanDescriptor_registerTest.java
  src/test/java/org/multitenant/partition/MultiTenantPartitionTest.java
  src/test/java/org/tests/basic/MainDbBoolean.java
  src/test/java/org/tests/changelog/TestChangeLog.java
  src/test/java/org/tests/persistencecontext/TestPersistenceContextServerConfig.java
  src/test/java/org/tests/readaudit/TestReadAudit.java
  src/test/java/org/tests/transaction/TestAutoCommitDataSource.java
  src/test/java/org/tests/transaction/TestExplicitTransactionMode.java
Labels: refactor

#1602 ENH: A query on inherited beans can be restricted to the subtype of one of its children
  src/main/java/io/ebean/Query.java
  src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  src/test/java/org/tests/inheritance/TestInheritanceQuery.java
Labels: enhancement

#1609 FIX: insert in batch OneToOne relationship
  src/main/java/io/ebeaninternal/server/persist/BatchControl.java
  src/test/java/org/tests/batchinsert/TestBatchInsertOneToOne.java
  src/test/java/org/tests/batchinsert/o2o/MeterAddressData.java
  src/test/java/org/tests/batchinsert/o2o/MeterContractData.java
  src/test/java/org/tests/batchinsert/o2o/MeterSpecialNeedsClient.java
  src/test/java/org/tests/batchinsert/o2o/MeterSpecialNeedsContact.java
  src/test/java/org/tests/batchinsert/o2o/MeterVersion.java
Labels: bug
