Repository ebean-orm/ebean, pull requests merged in 2019-04, with the labels that each got.

#1668 Fix check constraint support for MariaDB >= 10.2.1
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/ClickHouseDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/ClickHouseTableDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/MySqlDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl.java
  src/test/resources/dbmigration/migrationtest/db2/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/mysql/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/mysql/1.1.sql
  src/test/resources/dbmigration/migrationtest/mysql/1.3.sql
Labels: behaviour change, refactor

#1687 Fix implicit conversion from array to string
  src/main/java/io/ebeaninternal/server/type/bindcapture/BindCaptureTypes.java
Labels: refactor

#1688 Remove useless comparison test
  src/main/java/io/ebean/config/dbplatform/sqlserver/SqlServer2005SqlLimiter.java
  src/main/java/io/ebean/config/dbplatform/sqlserver/SqlServerSqlLimiter.java
  src/main/java/io/ebeaninternal/server/query/CQueryPlanRawSql.java
Labels: refactor

#1690 #1686 - Change the default JSON format to ISO8601 for date and datetime types (from epoch millis)
  src/main/java/io/ebean/config/ServerConfig.java
  src/test/java/io/ebean/config/ServerConfigTest.java
  src/test/java/io/ebeaninternal/server/deploy/TestDiffHelpInsertSimple.java
  src/test/java/io/ebeaninternal/server/type/ScalarTypeLocalDateTest.java
Labels: behaviour change, documentation, refactor
