Repository ebean-orm/ebean, pull requests merged in 2020-02, with the labels that each got.

#1927 Fix cache emptylist and Fix / improvement for UUIDv1Generator mac address detection
  src/main/java/io/ebeaninternal/server/idgen/UuidV1IdGenerator.java
  src/main/java/io/ebeaninternal/server/query/CQueryEngine.java
Labels: bug

#1928 FIX: Regression of #1775 - set date for other platforms (non MySQL) broken, when ebean.dataTimeZone is set to GMT
  src/main/java/io/ebeaninternal/server/core/timezone/DataTimeZone.java
  src/main/java/io/ebeaninternal/server/core/timezone/LocalDataTimeZone.java
  src/main/java/io/ebeaninternal/server/type/DataBind.java
  src/main/java/io/ebeaninternal/server/type/RsetDataReader.java
  src/test/java/org/tests/model/types/SomeNewTypesBean.java
  src/test/java/org/tests/types/TestNewTypes.java
Labels: bug

#1925 #1924 - Refactor for Transaction profiling - base on ProfileLocation / remove profileId
  pom.xml
  src/main/java/io/ebean/ProfileLocation.java
  src/main/java/io/ebean/Query.java
  src/main/java/io/ebean/plugin/BeanType.java
  src/main/java/io/ebeaninternal/api/SpiProfileHandler.java
  src/main/java/io/ebeaninternal/api/SpiQuery.java
  src/main/java/io/ebeaninternal/server/core/PersistRequest.java
  src/main/java/io/ebeaninternal/server/core/PersistRequestBean.java
  src/main/java/io/ebeaninternal/server/core/PersistRequestCallableSql.java
  src/main/java/io/ebeaninternal/server/core/PersistRequestOrmUpdate.java
  src/main/java/io/ebeaninternal/server/core/PersistRequestUpdateSql.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
  src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanDescriptor.java
  src/main/java/io/ebeaninternal/server/profile/BasicProfileLocation.java
  src/main/java/io/ebeaninternal/server/profile/DProfileLocation.java
  src/main/java/io/ebeaninternal/server/query/CQuery.java
  src/main/java/io/ebeaninternal/server/query/CQueryFetchSingleAttribute.java
  src/main/java/io/ebeaninternal/server/query/CQueryRowCount.java
  src/main/java/io/ebeaninternal/server/query/CQueryUpdate.java
  src/main/java/io/ebeaninternal/server/query/DefaultFetchGroupQuery.java
  src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  src/main/java/io/ebeaninternal/server/transaction/DefaultProfileHandler.java
  src/main/java/io/ebeaninternal/server/transaction/DefaultProfileStream.java
  src/main/java/io/ebeaninternal/server/transaction/NoopProfileHandler.java
  src/main/java/io/ebeaninternal/server/transaction/ProfileStream.java
  src/main/java/io/ebeaninternal/server/transaction/TransactionManager.java
  src/main/java/io/ebeaninternal/server/transaction/TransactionProfile.java
  src/test/java/io/ebeaninternal/server/profile/BasicProfileLocationTest.java
  src/test/java/io/ebeaninternal/server/transaction/DefaultProfileHandlerTest.java
  src/test/java/org/tests/profile/ProfileLocationTest.java
Labels: refactor

#1946 Deprecate orderBy() migrate to order()
  src/main/java/io/ebean/DB.java
  src/main/java/io/ebean/Database.java
  src/main/java/io/ebean/Ebean.java
  src/main/java/io/ebean/ExpressionList.java
  src/main/java/io/ebean/ExtendedServer.java
  src/main/java/io/ebean/Finder.java
  src/main/java/io/ebean/Pairs.java
  src/main/java/io/ebean/Query.java
  src/main/java/io/ebean/QueryIterator.java
  src/main/java/io/ebeaninternal/api/LoadManyRequest.java
  src/main/java/io/ebeaninternal/server/grammer/EqlAdapter.java
  src/main/java/io/ebeaninternal/server/query/CQueryEngine.java
  src/test/java/io/ebean/DtoQueryFromOrmTest.java
  src/test/java/io/ebean/EbeanServer_eqlTest.java
  src/test/java/io/ebeaninternal/server/cache/CachedBeanDataSerializeTest.java
  src/test/java/org/tests/aggregateformula/TestAggregateFormula.java
  src/test/java/org/tests/basic/TestLazyLoadInCache.java
  src/test/java/org/tests/batchload/TestQueryJoin.java
  src/test/java/org/tests/compositekeys/TestCKeyLazyLoad.java
  src/test/java/org/tests/expression/bitwise/TestBitwiseExpressions.java
  src/test/java/org/tests/inheritance/bothsides/TestInheritanceBothSides.java
  src/test/java/org/tests/model/basic/cache/TestCacheViaComplexNaturalKey.java
  src/test/java/org/tests/model/basic/cache/TestCacheViaComplexNaturalKey3.java
  src/test/java/org/tests/model/pview/TestPview.java
  src/test/java/org/tests/model/selfref/TestSelfRefExample.java
  src/test/java/org/tests/model/selfref/TestTextJsonSelfRef.java
  src/test/java/org/tests/persistencecontext/TestPersistenceContextScopeUsingOrders.java
  src/test/java/org/tests/query/TestAddOrderByWithFirstRowsMaxRows.java
  src/test/java/org/tests/query/TestExprNestedDisjunction.java
  src/test/java/org/tests/query/TestLimitAlterFetchMany.java
  src/test/java/org/tests/query/TestManyWhereJoin.java
  src/test/java/org/tests/query/TestOuterJoin.java
  src/test/java/org/tests/query/TestQueryFilterMany.java
  src/test/java/org/tests/query/TestQueryFindEach.java
  src/test/java/org/tests/query/TestQueryFindEachWhile.java
  src/test/java/org/tests/query/TestQueryFindPagedList.java
  src/test/java/org/tests/query/TestQueryFindVisit.java
  src/test/java/org/tests/query/TestQueryOrderById.java
  src/test/java/org/tests/query/aggregation/TestAggregationCount.java
  src/test/java/org/tests/query/orderby/TestOrderByClear.java
  src/test/java/org/tests/query/orderby/TestOrderByOnComplex.java
  src/test/java/org/tests/query/orderby/TestOrderByWithDistinct.java
  src/test/java/org/tests/query/other/TestQueryConversationRowCount.java
  src/test/java/org/tests/query/other/TestQueryRowCountWithMany.java
  src/test/java/org/tests/query/other/TestQuerySingleAttribute.java
  src/test/java/org/tests/rawsql/TestRawSqlOrmQuery.java
Labels: deprecated-api

#1948 ENH: Add query.usingDatabase(database)
  src/main/java/io/ebean/Query.java
  src/main/java/io/ebeaninternal/server/query/DefaultFetchGroupQuery.java
  src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  src/test/java/io/ebeaninternal/server/transaction/DefaultTransactionThreadLocalTest.java
  src/test/java/org/tests/basic/TestQueryUsingConnection.java
Labels: enhancement

#1954 Add JSON expression handing for MySql - MySqlDbExpression.json
  src/main/java/io/ebeaninternal/server/expression/platform/MySqlDbExpression.java
  src/test/java/io/ebeaninternal/server/expression/platform/MySqlDbExpressionTest.java
Labels: bug

#1923 Remove io.ebean.meta.MetricType as it is unnecessary
  src/main/java/io/ebean/meta/MetaMetric.java
  src/main/java/io/ebean/meta/MetricData.java
  src/main/java/io/ebean/meta/MetricType.java
  src/main/java/io/ebean/metric/MetricFactory.java
  src/main/java/io/ebeaninternal/api/ExtraMetrics.java
  src/main/java/io/ebeaninternal/server/cache/DefaultServerCache.java
  src/main/java/io/ebeaninternal/server/core/DumpMetricsData.java
  src/main/java/io/ebeaninternal/server/deploy/BeanIudMetrics.java
  src/main/java/io/ebeaninternal/server/dto/DtoMappingRequest.java
  src/main/java/io/ebeaninternal/server/persist/DefaultPersistExecute.java
  src/main/java/io/ebeaninternal/server/profile/DCountMetric.java
  src/main/java/io/ebeaninternal/server/profile/DMetricFactory.java
  src/main/java/io/ebeaninternal/server/profile/DProfileLocationFactory.java
  src/main/java/io/ebeaninternal/server/profile/DQueryPlanMetric.java
  src/main/java/io/ebeaninternal/server/profile/DTimeMetricStats.java
  src/main/java/io/ebeaninternal/server/profile/DTimedMetric.java
  src/main/java/io/ebeaninternal/server/profile/DTimedMetricMap.java
  src/main/java/io/ebeaninternal/server/query/CQueryPlan.java
  src/main/java/io/ebeaninternal/server/query/CQueryPlanStats.java
  src/main/java/io/ebeaninternal/server/query/DefaultRelationalQueryEngine.java
  src/main/java/io/ebeaninternal/server/transaction/TransactionManager.java
  src/test/java/io/ebean/BaseTestCase.java
  src/test/java/io/ebeaninternal/server/deploy/BeanIudMetricsTest.java
  src/test/java/io/ebeaninternal/server/profile/BasicProfileLocationTest.java
  src/test/java/io/ebeaninternal/server/profile/DTimedMetricMapTest.java
  src/test/java/io/ebeaninternal/server/profile/DTimedMetricTest.java
  src/test/java/io/ebeaninternal/server/profile/SortMetricTest.java
Labels: breaking-api

#1944 #1943 - Use limit & offset via setFirstRow() and setMaxRows() on filterMany()
  src/main/java/io/ebean/ExpressionList.java
  src/main/java/io/ebeaninternal/api/SpiExpressionList.java
  src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  src/main/java/io/ebeaninternal/server/expression/FilterExpressionList.java
  src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  src/main/java/io/ebeaninternal/server/querydefn/OrmQueryProperties.java
  src/test/java/org/tests/basic/TestLimitQuery.java
  src/test/java/org/tests/query/TestQueryFilterMany.java
  src/test/java/org/tests/query/TestQueryFindIterate.java
Labels: refactor

#1951 OraclePlatform update (ANSI row limiting with OFFSET), Oracle11Platform for old behaviour
  pom.xml
  src/main/java/io/ebean/config/dbplatform/RowNumberSqlLimiter.java
  src/main/java/io/ebean/config/dbplatform/RownumSqlLimiter.java
  src/main/java/io/ebean/config/dbplatform/oracle/Oracle11Platform.java
  src/main/java/io/ebean/config/dbplatform/oracle/OracleAnsiSqlRowsLimiter.java
  src/main/java/io/ebean/config/dbplatform/oracle/OraclePlatform.java
  src/main/java/io/ebean/config/dbplatform/oracle/OracleRownumSqlLimiter.java
  src/main/java/io/ebeaninternal/dbmigration/DefaultDbMigration.java
  src/main/java/io/ebeaninternal/server/core/DatabasePlatformFactory.java
  src/main/java/io/ebeaninternal/server/core/InternalConfiguration.java
  src/main/java/io/ebeaninternal/server/core/PlatformDdlBuilder.java
  src/main/java/io/ebeaninternal/server/expression/platform/BaseDbExpression.java
  src/main/java/io/ebeaninternal/server/expression/platform/DbExpressionHandlerFactory.java
  src/main/java/io/ebeaninternal/server/expression/platform/H2DbExpression.java
  src/main/java/io/ebeaninternal/server/expression/platform/OracleDbExpression.java
  src/main/java/io/ebeaninternal/server/expression/platform/PostgresDbExpression.java
  src/test/java/io/ebean/BaseTestCase.java
  src/test/java/io/ebean/EbeanServer_eqlTest.java
  src/test/java/io/ebeaninternal/server/expression/platform/H2DbExpressionTest.java
  src/test/java/io/ebeaninternal/server/expression/platform/OracleDbExpressionTest.java
  src/test/java/io/ebeaninternal/server/expression/platform/PostgresDbExpressionTest.java
  src/test/java/main/StartOracle.java
  src/test/java/org/tests/batchinsert/TestBatchInsertFlush.java
  src/test/java/org/tests/lazyforeignkeys/MainEntity.java
  src/test/java/org/tests/lazyforeignkeys/TestLazyForeignKeys.java
  src/test/java/org/tests/model/basic/cache/TestCacheViaComplexNaturalKey3.java
  src/test/java/org/tests/model/history/TestHistoryOneToMany.java
  src/test/java/org/tests/model/nofk/EUserNoFkSoftDel.java
  src/test/java/org/tests/model/nofk/TestNoFk.java
  src/test/java/org/tests/model/onetoone/TestOneToOneOrphanRemove.java
  src/test/java/org/tests/query/TestQueryOrderById.java
  src/test/java/org/tests/query/finder/TestCustomerFinder.java
  src/test/java/org/tests/query/other/TestQuerySingleAttribute.java
  src/test/java/org/tests/rawsql/TestRawSqlOrmQuery.java
  src/test/java/org/tests/transaction/TestNestedSubTransaction.java
Labels: behaviour change, refactor

#1957 #1955 #1956 SqlQuery.mapToScalar() and SqlQuery.mapTo(RowMapper)
  src/main/java/io/ebean/RowMapper.java
  src/main/java/io/ebean/SqlQuery.java
  src/main/java/io/ebeaninternal/server/querydefn/DefaultRelationalQuery.java
  src/test/java/org/tests/basic/TestTransient.java
  src/test/java/org/tests/basic/type/TestSqlRowUUID.java
  src/test/java/org/tests/query/sqlquery/SqlQueryTests.java
  src/test/java/org/tests/update/TestSqlUpdateExceptions.java
Labels: deprecated-api, refactor

#1961 Refactor PlatformDdl separate call to asIdentityColumn()
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/AbstractHanaDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/DbTriggerBasedHistoryDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/HanaHistoryDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/MySqlDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/SqlServerDdl.java
  src/test/java/io/ebean/config/dbplatform/H2PlatformTest.java
  src/test/java/io/ebean/config/dbplatform/HanaPlatformTest.java
  src/test/java/io/ebean/config/dbplatform/MySqlPlatformTest.java
  src/test/java/io/ebean/config/dbplatform/OraclePlatformTest.java
  src/test/java/io/ebean/config/dbplatform/PostgresPlatformTest.java
  src/test/java/io/ebean/config/dbplatform/SqlserverPlatformTest.java
Labels: refactor
