Repository ebean-orm/ebean, pull requests merged in 2020-04, with the labels that each got.

#1985 Update is missing for relations with @OrderColumn from a tree depth > 1
  src/main/java/io/ebeaninternal/server/persist/SaveManyBeans.java
  src/test/java/org/tests/cascade/TestOrderedList.java
  src/test/java/org/tests/order/OrderReferencedChild.java
  src/test/java/org/tests/order/OrderToy.java
  src/test/java/org/tests/order/TestOrderColumn.java
Labels: bug

#1986 @OrderColumn is ignored on relations referencing a abstract inheritance-model
  src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
  src/test/java/org/tests/inheritance/TestInheritanceOrderColumn.java
  src/test/java/org/tests/inheritance/order/OrderMasterInheritance.java
  src/test/java/org/tests/inheritance/order/OrderedA.java
  src/test/java/org/tests/inheritance/order/OrderedB.java
  src/test/java/org/tests/inheritance/order/OrderedParent.java
Labels: bug

#1976 Change OraclePlatform to default to use Identity (rather than sequence)
  pom.xml
  src/main/java/io/ebean/config/dbplatform/oracle/Oracle11Platform.java
  src/main/java/io/ebean/config/dbplatform/oracle/OraclePlatform.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/OracleDdl.java
  src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl.java
  src/main/java/io/ebeaninternal/server/core/PlatformDdlBuilder.java
  src/test/ddl-review/oracle-create-all.sql
  src/test/ddl-review/oracle-drop-all.sql
  src/test/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/OracleDdlTest.java
  src/test/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl_AlterColumnTest.java
  src/test/resources/dbmigration/migrationtest/oracle/1.0__initial.sql
  src/test/resources/dbmigration/migrationtest/oracle/1.1.sql
  src/test/resources/dbmigration/migrationtest/oracle/1.3.sql
Labels: behaviour change

#1993 Remove autoCommitMode and explicitTransactionBeginMode
  src/main/java/io/ebean/config/ServerConfig.java
  src/main/java/io/ebeaninternal/server/core/DefaultContainer.java
  src/main/java/io/ebeaninternal/server/core/InternalConfiguration.java
  src/main/java/io/ebeaninternal/server/transaction/AutoCommitJdbcTransaction.java
  src/main/java/io/ebeaninternal/server/transaction/AutoCommitTransactionManager.java
  src/main/java/io/ebeaninternal/server/transaction/ExplicitJdbcTransaction.java
  src/main/java/io/ebeaninternal/server/transaction/ExplicitTransactionManager.java
  src/test/java/org/tests/transaction/TestAutoCommitDataSource.java
  src/test/java/org/tests/transaction/TestExplicitTransactionMode.java
Labels: removed-api
