Repository ebean-orm/ebean, pull requests merged in 2021-07, with the labels that each got.

#2260 Fix additional autotune runtimeExceptions due to toString() calls instead of asString()
  ebean-autotune/src/main/java/io/ebeaninternal/server/autotune/service/AutoTuneDiffCollection.java
  ebean-autotune/src/main/java/io/ebeaninternal/server/autotune/service/TunedQueryInfo.java
Labels: bug

#2256 Improved @Where support, especially for Many-to-many tables
  ebean-core/pom.xml
  ebean-core/src/main/java/io/ebeaninternal/api/LoadManyRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorMap.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocMany.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/DbSqlContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/TableJoin.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanPropertyAssoc.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/meta/DeployTableJoin.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationAssocManys.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationAssocOnes.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationFields.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationParser.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultDbSqlContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/SqlTreeNodeManyRoot.java
  ebean-core/src/test/java/org/tests/model/m2m/MnyEdge.java
  ebean-core/src/test/java/org/tests/model/m2m/MnyNode.java
  ebean-core/src/test/java/org/tests/model/m2m/TestM2MWithWhere.java
  ebean-core/src/test/java/org/tests/o2m/OmBasicParent.java
  ebean-core/src/test/java/org/tests/o2m/TestOneToManyWhere.java
  ebean-core/src/test/java/org/tests/query/TestImplicitJoinOnParentRelationship.java
  ebean-core/src/test/java/org/tests/query/TestManyWhereJoin.java
  ebean-core/src/test/java/org/tests/query/TestQueryFilterMany.java
  ebean-core/src/test/java/org/tests/query/TestQueryIsNull.java
  ebean-core/src/test/java/org/tests/query/other/TestQueryRawExpressionMany.java
  ebean-core/src/test/java/org/tests/query/other/TestQueryRowCountWithMany.java
  ebean-core/src/test/java/org/tests/query/other/TestQuerySingleAttribute.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/model/build/ModelBuildPropertyVisitor.java
Labels: behaviour change, bug

#2267 Retrieve (C|B)LOB on SqlRow construction
  ebean-core/src/main/java/io/ebeaninternal/server/rawsql/DRawSqlService.java
  ebean-core/src/test/java/io/ebeaninternal/server/rawsql/TestRawSqlBuilder.java
Labels: behaviour change, bug, reason-for-version-bump

#2273 #2272 Fix for collection with orphanRemoval (such that equals/hashCode isn't use)
  ebean-api/src/main/java/io/ebean/common/ModifyHolder.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/SaveManyBeans.java
  ebean-core/src/test/java/io/ebean/common/BeanListTest.java
  ebean-core/src/test/java/io/ebean/common/BeanMapTest.java
  ebean-core/src/test/java/io/ebean/common/BeanSetTest.java
  ebean-core/src/test/java/org/tests/m2m/TestM2MModifyTest.java
  ebean-core/src/test/java/org/tests/model/orphanremoval/OmBeanListChild.java
  ebean-core/src/test/java/org/tests/model/orphanremoval/OmBeanListParent.java
  ebean-core/src/test/java/org/tests/model/orphanremoval/TestOrphanRemovalOverwrite.java
Labels: bug

#2282 Treat json Jackson collections the same wrt mutation detection
  ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/DefaultTypeManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/InitObjectMapper.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonObjectMapper.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/TypeJsonManager.java
  ebean-core/src/test/java/io/ebean/config/ServerConfigTest.java
  ebean-core/src/test/java/org/tests/json/TestDbJson_List.java
  ebean-core/src/test/java/org/tests/model/json/EBasicJsonList.java
Labels: refactor
