Repository ebean-orm/ebean, pull requests merged in 2021-09, with the labels that each got.

#2337 Query bean PByteArray type for byte[]
  ebean-querybean/src/main/java/io/ebean/typequery/PByteArray.java
  ebean-querybean/src/test/java/org/example/domain/Customer.java
  ebean-querybean/src/test/java/org/querytest/QCustomerByteArrayTest.java
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/PropertyTypeMap.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/PropertyTypeMap.java
Labels: enhancement

#2338 NEW: DeleteIdRequest can return beanType
  ebean-api/src/main/java/io/ebean/event/BeanDeleteIdRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/DefaultPersister.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/DeleteIdRequest.java
Labels: enhancement

#2340 #2335 - L2 cache be triggered by in ?
  ebean-core/src/main/java/io/ebeaninternal/api/LoadBeanRequest.java
  ebean-core/src/main/java/io/ebeaninternal/api/LoadManyRequest.java
  ebean-core/src/main/java/io/ebeaninternal/api/LoadRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultBeanLoader.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultOrmQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-core/src/test/java/org/tests/basic/TestReadOnlyPropagation.java
  ebean-core/src/test/java/org/tests/batchload/TestBatchLazyWithCacheHits.java
  ebean-core/src/test/java/org/tests/batchload/TestQueryJoin.java
  ebean-core/src/test/java/org/tests/batchload/TestSecondaryQueries.java
  ebean-core/src/test/java/org/tests/cache/TestBeanFetchJoinCache.java
  ebean-core/src/test/java/org/tests/model/basic/cache/ESoftWithCache.java
  ebean-core/src/test/java/org/tests/model/basic/cache/TestCacheWithSoftDelete.java
  ebean-core/src/test/java/org/tests/rawsql/nativesql/TestNativeSqlBasic.java
Labels: bug

#2365 Allow caching of exists-queries
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQuery.java
  ebean-core/src/main/java/io/ebeaninternal/api/TxnProfileEventCodes.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-test/src/test/java/org/tests/cache/TestQueryCache.java
Labels: bug

#2373 Allow post-processing in BeanFindController
  ebean-api/src/main/java/io/ebean/event/BeanFindController.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultOrmQueryEngine.java
  ebean-test/src/test/java/io/ebean/event/BeanFindControllerTest.java
  ebean-test/src/test/java/org/tests/model/controller/FindControllerMain.java
  ebean-test/src/test/java/org/tests/model/controller/SoftRefA.java
  ebean-test/src/test/java/org/tests/model/controller/SoftRefB.java
  ebean-test/src/test/java/org/tests/model/controller/TestBeanFindController.java
Labels: enhancement

#2378 #2377 - Wrong order in batch save - Fix to transaction depth
  ebean-core/src/main/java/io/ebeaninternal/api/SpiTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiTransactionProxy.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/BatchControl.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/DefaultPersister.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/ImplicitReadOnlyTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/JdbcTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/NoTransaction.java
  ebean-test/src/test/java/io/ebeaninternal/server/transaction/TransactionTest.java
  ebean-test/src/test/java/org/tests/model/basic/relates/Relation1.java
  ebean-test/src/test/java/org/tests/model/basic/relates/Relation2.java
  ebean-test/src/test/java/org/tests/model/basic/relates/Relation3.java
  ebean-test/src/test/java/org/tests/model/basic/relates/Relation4.java
Labels: bug

#2381 Add module-info support via multi-version jar
  ebean-api/pom.xml
  ebean-api/src/main/java/io/ebean/config/ClassLoadConfig.java
  ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java
  ebean-api/src/main/java9/module-info.java
  ebean-api/src/main/resources/META-INF/MANIFEST.MF
  ebean-autotune/pom.xml
  ebean-autotune/src/main/java9/module-info.java
  ebean-autotune/src/main/resources/META-INF/MANIFEST.MF
  ebean-core-type/pom.xml
  ebean-core-type/src/main/java9/module-info.java
  ebean-core/pom.xml
  ebean-core/src/main/java/io/ebeaninternal/server/core/ClassPathScanners.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/InitDataSource.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/InternalConfiguration.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/ServiceUtil.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/DefaultTypeManager.java
  ebean-core/src/main/java9/module-info.java
  ebean-core/src/main/resources/META-INF/MANIFEST.MF
  ebean-ddl-generator/pom.xml
  ebean-ddl-generator/src/main/java9/module-info.java
  ebean-ddl-generator/src/main/resources/META-INF/MANIFEST.MF
  ebean-externalmapping-api/pom.xml
  ebean-externalmapping-api/src/main/java9/module-info.java
  ebean-externalmapping-api/src/main/resources/META-INF/MANIFEST.MF
  ebean-externalmapping-xml/pom.xml
  ebean-externalmapping-xml/src/main/java9/module-info.java
  ebean-externalmapping-xml/src/main/resources/META-INF/MANIFEST.MF
  ebean-postgis/pom.xml
  ebean-postgis/src/main/java9/module-info.java
  ebean-querybean/pom.xml
  ebean-querybean/src/main/java9/module-info.java
  ebean-querybean/src/main/resources/META-INF/MANIFEST.MF
  ebean-redis/pom.xml
  ebean-redis/src/main/java9/module-info.java
  ebean-test/pom.xml
  ebean-test/src/main/java9/module-info.java
  ebean-test/src/main/resources/META-INF/MANIFEST.MF
  ebean/pom.xml
  ebean/src/main/java9/module-info.java
  ebean/src/main/resources/META-INF/MANIFEST.MF
  querybean-generator/pom.xml
  querybean-generator/src/main/java9/module-info.java
Labels: refactor

#2382 Refactor rename TransactionManager methods
  ebean-core/src/main/java/io/ebeaninternal/api/SpiTransactionManager.java
  ebean-core/src/main/java/io/ebeaninternal/api/TransactionEvent.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPlanManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/DefaultTransactionScopeManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/ExternalTransactionScopeManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/JdbcTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/JtaTransactionManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/PostCommitProcessing.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/TransactionManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/TransactionScopeManager.java
  ebean-test/src/test/java/io/ebean/BaseTestCase.java
  ebean-test/src/test/java/io/ebeaninternal/server/transaction/TransactionManagerTest.java
Labels: refactor

#2380 WIP: Try to fix ClassCastException in isToManyDirty() check
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-test/src/test/java/org/tests/transparentpersist/TestTransparentPersist.java
  tests/pom.xml
  tests/test-kotlin/pom.xml
  tests/test-kotlin/src/test/kotlin/io/ebean/test/kotlin/TransparentPersistenceTest.kt
  tests/test-kotlin/src/test/kotlin/org/example/order/Customer.kt
  tests/test-kotlin/src/test/kotlin/org/example/order/Order.kt
  tests/test-kotlin/src/test/kotlin/org/example/order/OrderItem.kt
  tests/test-kotlin/src/test/resources/application-test.yaml
  tests/test-kotlin/src/test/resources/logback-test.xml
Labels: bug
