Repository ebean-orm/ebean, pull requests merged in 2021-02, with the labels that each got.

#2152 Fix to only cancel query once
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-core/src/test/java/org/tests/query/TestQueryFindFutureList.java
Labels: bug

#2160 #2156 - Using @OneToOne(targetEntity...) with Interface field results…
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanPropertyAssoc.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanPropertyAssocMany.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationAssoc.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationAssocManys.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationAssocOnes.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/DeployCreateProperties.java
  ebean-core/src/test/java/org/tests/basic/TestManyOneInterface.java
  ebean-core/src/test/java/org/tests/model/interfaces/Address.java
  ebean-core/src/test/java/org/tests/model/interfaces/IPersona.java
  ebean-core/src/test/java/org/tests/model/interfaces/Persona.java
  ebean-core/src/test/java/org/tests/model/interfaces/TestTargetEntity.java
Labels: bug

#2130 Ignore special kotlin collection types
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/SimpleQueryBeanWriter.java
Labels: behaviour change

#2159 Improve internal calculation of orm query plan hash key (Require use of inline hints like +query(50) to be comma delimited with properties)
  ebean-autotune/src/test/java/io/ebeaninternal/server/autotune/service/ProfileOriginTest.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/SqlTreeBuilder.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryDetail.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryPlanKey.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryProperties.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryPropertiesParser.java
  ebean-core/src/main/java/io/ebeaninternal/server/rawsql/DRawSqlColumnsParser.java
  ebean-core/src/main/java/io/ebeaninternal/server/util/DSelectColumnsParser.java
  ebean-core/src/test/java/io/ebean/plugin/BeanTypeTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/querydefn/OrmQueryPropertiesParserTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/querydefn/OrmQueryPropertiesTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/util/DSelectColumnsParserTest.java
  ebean-core/src/test/java/org/tests/batchload/TestQueryJoin.java
Labels: behaviour change, refactor

#2164 Deprecate the mutating methods of FetchConfig to migrate to the static factory methods
  ebean-api/src/main/java/io/ebean/FetchConfig.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryProperties.java
Labels: deprecated-api

#2163 Remove support for "query hints" like +query(50)
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryProperties.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryPropertiesParser.java
  ebean-core/src/test/java/io/ebeaninternal/server/grammer/EqlParserTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/querydefn/OrmQueryPropertiesParserTest.java
  ebean-core/src/test/java/org/tests/batchload/TestLazyJoin.java
  ebean-core/src/test/java/org/tests/batchload/TestQueryJoin.java
Labels: behaviour change, breaking-api

#2167 Refactor query internals to reduce property parsing for partial select and fetch
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQuery.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQueryFetch.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DFetchGroupBuilder.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultFetchGroupQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryDetail.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryProperties.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryPropertiesParser.java
  ebean-core/src/test/java/io/ebeaninternal/server/querydefn/OrmQueryPropertiesParserTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/querydefn/OrmQueryPropertiesTest.java
  ebean-core/src/test/java/org/tests/basic/lob/TestBasicClobNoVer.java
  ebean-querybean/pom.xml
  ebean-querybean/src/main/java/io/ebean/typequery/TQAssocBean.java
  ebean-querybean/src/main/java/io/ebean/typequery/TQRootBean.java
  ebean-querybean/src/test/java/org/querytest/QOrderTest.java
Labels: refactor

#2171 #2169 - Refactor internals after #2170 , tidy internals for javax/jakarta validation annotation reading
  ebean-api/pom.xml
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanProperty.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationAssocOnes.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationFields.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationParser.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/InitMetaJakartaValidationAnnotation.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/InitMetaJavaxValidationAnnotation.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/ReadAnnotationConfig.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/ReadAnnotations.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/ReadValidationAnnotations.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/ReadValidationAnnotationsJakarta.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/ReadValidationAnnotationsJavax.java
Labels: refactor

#2175 #2174 - Entity beans with @Cache + @DbArray of enums (or UUID or Integer) not converted to enums (come back as String)
  ebean-core/src/main/java/io/ebeaninternal/server/type/ArrayElementConverter.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ArrayElementConverterEnum.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeArrayList.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeArraySet.java
  ebean-core/src/test/java/io/ebeaninternal/server/type/ScalarTypeArrayListTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/type/ScalarTypeArraySetH2Test.java
  ebean-core/src/test/java/org/tests/model/array/EArrayBean.java
  ebean-core/src/test/java/org/tests/model/array/EArraySetBean.java
  ebean-core/src/test/java/org/tests/model/array/TestDbArray_asSet.java
  ebean-core/src/test/java/org/tests/model/array/TestDbArray_basic.java
Labels: bug
