Repository ebean-orm/ebean, pull requests merged in 2021-08, with the labels that each got.

#2288 Change query metric hash from MD5 of sql + name + loc to Checksum of sql (+ rename to sqlHash)
  ebean-api/src/main/java/io/ebean/meta/MetaQueryMetric.java
  ebean-api/src/main/java/io/ebean/meta/MetaQueryPlan.java
  ebean-api/src/main/java/io/ebean/meta/MetricData.java
  ebean-api/src/main/java/io/ebean/meta/QueryPlanInit.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQueryPlan.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetrics.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetricsData.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetricsJson.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DQueryPlanMeta.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DQueryPlanMetric.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPlan.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPlanStats.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DQueryPlanOutput.java
  ebean-core/src/main/java/io/ebeaninternal/server/util/Md5.java
  ebean-core/src/test/java/io/ebeaninternal/server/util/Md5Test.java
  ebean-core/src/test/java/org/tests/query/finder/TestCustomerFinder.java
Labels: breaking-api

#2289 Refactor io.ebean.meta API, method rename with deprecation
  ebean-api/src/main/java/io/ebean/meta/AbstractMetricVisitor.java
  ebean-api/src/main/java/io/ebean/meta/BasicMetricVisitor.java
  ebean-api/src/main/java/io/ebean/meta/MetaCountMetric.java
  ebean-api/src/main/java/io/ebean/meta/MetaMetric.java
  ebean-api/src/main/java/io/ebean/meta/MetaQueryMetric.java
  ebean-api/src/main/java/io/ebean/meta/MetaQueryPlan.java
  ebean-api/src/main/java/io/ebean/meta/MetaTimedMetric.java
  ebean-api/src/main/java/io/ebean/meta/MetricVisitor.java
  ebean-api/src/main/java/io/ebean/meta/QueryPlanInit.java
  ebean-api/src/main/java/io/ebean/meta/QueryPlanRequest.java
  ebean-api/src/main/java/io/ebean/meta/ServerMetrics.java
  ebean-api/src/main/java/io/ebean/meta/ServerMetricsAsJson.java
  ebean-api/src/main/java/io/ebean/meta/SortMetric.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultQueryPlanListener.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetrics.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetricsData.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetricsJson.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DCountMetric.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DQueryPlanMetric.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DTimeMetricStats.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DTimedMetric.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DTimedProfileLocation.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPlanRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPlanStats.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DQueryPlanOutput.java
  ebean-core/src/test/java/io/ebean/BaseTestCase.java
  ebean-core/src/test/java/io/ebean/DtoQuery2Test.java
  ebean-core/src/test/java/io/ebean/DtoQueryFromOrmTest.java
  ebean-core/src/test/java/io/ebean/DtoQueryTest.java
  ebean-core/src/test/java/io/ebean/UpdateQueryTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/deploy/BeanIudMetricsTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/profile/DTimedMetricMapTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/profile/DTimedMetricTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/profile/SortMetricTest.java
  ebean-core/src/test/java/org/tests/batchinsert/TestBatchInsertFlush.java
  ebean-core/src/test/java/org/tests/m2m/TestM2mDeleteObject.java
  ebean-core/src/test/java/org/tests/query/finder/TestCustomerFinder.java
  ebean-core/src/test/java/org/tests/query/sqlquery/SqlQueryTests.java
  ebean-core/src/test/java/org/tests/transaction/TestNestedMandatory.java
  ebean-core/src/test/java/org/tests/transaction/TestTransactionalReadOnly.java
  ebean-core/src/test/java/org/tests/update/TestSqlUpdateInTxn.java
  ebean-ddl-generator/src/test/java/io/ebean/BaseTestCase.java
  ebean-redis/src/main/java/io/ebean/redis/RedisCache.java
Labels: deprecated-api, refactor

#2294 #2293 - Metric hash back to MD5 of sql + name + loc (minus location file and line source) ~= Revert of #2288
  ebean-api/src/main/java/io/ebean/ProfileLocation.java
  ebean-api/src/main/java/io/ebean/meta/MetaQueryMetric.java
  ebean-api/src/main/java/io/ebean/meta/MetaQueryPlan.java
  ebean-api/src/main/java/io/ebean/meta/MetaTimedMetric.java
  ebean-api/src/main/java/io/ebean/meta/MetricData.java
  ebean-api/src/main/java/io/ebean/meta/QueryPlanInit.java
  ebean-api/src/main/java/io/ebean/metric/TimedMetricStats.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQueryPlan.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetrics.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetricsData.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DumpMetricsJson.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/BasicProfileLocation.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DProfileLocation.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DQueryPlanMeta.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DQueryPlanMetric.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DTimeMetricStats.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/UtilLocation.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPlan.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPlanStats.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DQueryPlanOutput.java
  ebean-core/src/main/java/io/ebeaninternal/server/util/Md5.java
  ebean-core/src/test/java/io/ebeaninternal/server/profile/BasicProfileLocationTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/profile/UtilLocationTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/util/Md5Test.java
  ebean-core/src/test/java/org/tests/profile/ProfileLocationTest.java
  ebean-core/src/test/java/org/tests/query/finder/TestCustomerFinder.java
Labels: refactor

#2297 FIX: Changelog-oldValue did not work for Json mutable properties
  ebean-api/src/main/java/io/ebean/bean/EntityBeanIntercept.java
  ebean-core/src/test/java/org/tests/changelog/TestChangeLog.java
  ebean-core/src/test/java/org/tests/model/basic/EBasicChangeLog.java
Labels: bug

#2295 Use MD5 for QueryBindHash
  ebean-core/src/main/java/io/ebeaninternal/api/BindHash.java
  ebean-core/src/main/java/io/ebeaninternal/api/BindParams.java
  ebean-core/src/main/java/io/ebeaninternal/api/HashQuery.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiExpression.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/AbstractTextExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/AllEqualsExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/ArrayContainsExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/ArrayIsEmptyExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/BetweenExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/BetweenPropertyExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/BitwiseExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/CaseInsensitiveEqualExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExampleExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/ExistsQueryExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/IdExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/IdInExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/InExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/InPairsExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/InQueryExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/InRangeExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/IsEmptyExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JsonPathExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/LikeExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/LogicExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/NativeILikeExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/NestedPathWrapperExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/NoopExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/NotExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/NullExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/RawExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/SimpleExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/HashCodeBindHash.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/MdBindHash.java
  ebean-core/src/test/java/io/ebeaninternal/server/expression/RawExpressionTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/querydefn/DefaultOrmQueryTest.java
  ebean-core/src/test/java/org/tests/cache/TestQueryCache.java
Labels: refactor

#2299 PushJson/PopJson did not work correctly, if null beans were involved
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonObjectMapper.java
  ebean-core/src/test/java/org/tests/json/TestDbJson_Jackson3.java
  ebean-core/src/test/java/org/tests/model/json/EBasicJsonMulti.java
Labels: bug

#2300 Enables select + exists for dynamic formula properties
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/SqlTreeBuilder.java
  ebean-core/src/test/java/org/tests/query/TestQueryAlias.java
Labels: bug

#2306 Use SoftReferences in Cache
  ebean-core/src/main/java/io/ebeaninternal/server/cache/DefaultServerCache.java
  ebean-core/src/main/java/io/ebeaninternal/server/cache/DefaultServerCacheConfig.java
  ebean-core/src/main/java/io/ebeaninternal/server/cache/DefaultServerQueryCache.java
Labels: refactor

#2310 FIX: mutation info is not restored on cache hit
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyJsonMapper.java
  ebean-core/src/test/java/org/tests/changelog/TestChangeLog.java
Labels: bug

#2316 Fix: setting json values to null was throwing a NPE when persisting
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonList.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonSet.java
  ebean-core/src/test/java/org/tests/json/TestJsonNullValues.java
Labels: bug

#2322 Fix for subqueries without where condition
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPredicates.java
  ebean-core/src/test/java/org/tests/query/TestQueryExists.java
  ebean-core/src/test/java/org/tests/query/TestSubQuery.java
Labels: bug

#2325 Modification of a OneToMany-Relation with @OrderColumn was not detected
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocMany.java
  ebean-core/src/test/java/org/tests/cascade/TestOrderedList.java
Labels: bug

#2329 @OrderdColum did not work properly with cached beans
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorCacheHelp.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/SaveManyBeans.java
  ebean-core/src/test/java/org/tests/cascade/OmCacheOrderedDetail.java
  ebean-core/src/test/java/org/tests/cascade/OmCacheOrderedMaster.java
  ebean-core/src/test/java/org/tests/cascade/TestOrderedList.java
Labels: bug

#2330 Make getSortOrder accessible in BeanState API
  ebean-api/src/main/java/io/ebean/BeanState.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultBeanState.java
Labels: enhancement

#2331 Fix for NPE in mutableNext in EBI
  ebean-api/src/main/java/io/ebean/bean/EntityBeanIntercept.java
  ebean-core/src/test/java/org/tests/json/TestJsonNullValues.java
Labels: bug
