Repository ebean-orm/ebean, pull requests merged in 2021-03, with the labels that each got.

#2180 Improved fix for #2179 - Fetch on nested one-to-many collectio…
  ebean-api/src/main/java/io/ebean/common/BeanSet.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/SqlTreeNodeBean.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/SqlTreeNodeManyRoot.java
Labels: refactor

#2185 add in(subQuery) support for query beans
  ebean-querybean/src/main/java/io/ebean/typequery/PBaseValueEqual.java
Labels: enhancement

#2183 added tests for findNative fetches
  ebean-core/src/test/java/org/tests/query/TestQueryFindNative.java
Labels: bug

#2191 ENH: Add Query findEach() with batch consumer
  ebean-api/src/main/java/io/ebean/ExpressionList.java
  ebean-api/src/main/java/io/ebean/ExtendedServer.java
  ebean-api/src/main/java/io/ebean/Query.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/OrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/SpiOrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultFetchGroupQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-core/src/test/java/io/ebeaninternal/api/TDSpiEbeanServer.java
  ebean-querybean/src/main/java/io/ebean/typequery/TQRootBean.java
  ebean-querybean/src/test/java/org/querytest/QCustomerTest.java
Labels: enhancement

#2190 Change ModuleInfoLoader API and querybean-generator for named default database
  ebean-api/src/main/java/io/ebean/config/ModuleInfoLoader.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultContainer.java
  kotlin-querybean-generator/pom.xml
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/SimpleModuleInfoWriter.java
  kotlin-querybean-generator/src/test/kotlin/io/ebean/querybean/generator/AddressTest.kt
  querybean-generator/src/main/java/io/ebean/querybean/generator/SimpleModuleInfoWriter.java
Labels: bug

#2198 Feature/json assert compare arrays
  ebean-test/src/main/java/io/ebean/test/CompareResult.java
  ebean-test/src/main/java/io/ebean/test/JsonAssertContains.java
  ebean-test/src/test/java/io/ebean/test/JsonAssertContainsTest.java
  ebean-test/src/test/resources/contains/array-multi-match-duplicate-props.json
  ebean-test/src/test/resources/contains/array-multi-match.json
  ebean-test/src/test/resources/contains/array-objects-shuffled.json
  ebean-test/src/test/resources/contains/array-objects.json
  ebean-test/src/test/resources/contains/nested-array-both.json
  ebean-test/src/test/resources/contains/nested-array-extraExpected.json
  ebean-test/src/test/resources/contains/nested-array-missExpected.json
  ebean-test/src/test/resources/contains/nested-array-ordering.json
  ebean-test/src/test/resources/contains/nested-array.json
  ebean-test/src/test/resources/contains/original-subset-modified.json
  ebean-test/src/test/resources/contains/original.json
Labels: refactor

#2204 Honor setLazyLoadBatchSize() when using FetchConfig.ofLazy() of unspecified size
  ebean-api/src/main/java/io/ebean/FetchConfig.java
  ebean-core/src/main/java/io/ebeaninternal/api/LoadContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/OrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadBaseContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadBeanContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadManyContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryEngine.java
  ebean-core/src/test/java/io/ebean/FetchConfigTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/grammer/ParseFetchConfigTest.java
  ebean-core/src/test/java/org/tests/query/TestQueryFindEach.java
Labels: bug
