Repository ebean-orm/ebean, pull requests merged in 2022-06, with the labels that each got.

#2706 ENH: Add support for findSingleAttributeSet()
  ebean-api/src/main/java/io/ebean/ExpressionList.java
  ebean-api/src/main/java/io/ebean/ExtendedServer.java
  ebean-api/src/main/java/io/ebean/Query.java
  ebean-autotune/src/main/java/io/ebeaninternal/server/autotune/service/BaseQueryTuner.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQuery.java
  ebean-core/src/main/java/io/ebeaninternal/api/TxnProfileEventCodes.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/OrmQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/OrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/SpiOrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryFetchSingleAttribute.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultFetchGroupQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultOrmQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiEbeanServer.java
  ebean-test/src/test/java/org/tests/cache/TestQueryCache.java
Labels: enhancement

#2708 Part 1: Fix read/write/query LocalTime values
  ebean-core/src/main/java/io/ebeaninternal/server/core/timezone/DataTimeZone.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/timezone/MySqlDataTimeZone.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/DataBind.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/RsetDataReader.java
  ebean-test/src/test/java/org/tests/timezone/LocalTimeTest.java
  ebean-test/src/test/java/org/tests/timezone/MLocalTime.java
Labels: bug

#2717 Support Postgres JSONB/JSON with String - @DbJsonb String content;
  ebean-core/src/main/java/io/ebeaninternal/server/type/DefaultTypeManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonString.java
  ebean-test/src/test/java/main/StartPostgres.java
  ebean-test/src/test/java/org/tests/json/TestDbJsonBStringType.java
  ebean-test/src/test/java/org/tests/json/TestDbJsonStringType.java
  ebean-test/src/test/java/org/tests/model/json/EBasicJsonBString.java
  ebean-test/src/test/java/org/tests/model/json/EBasicJsonString.java
  ebean-test/src/test/resources/logback-test.xml
Labels: bug

#2719 DDL - Refactor DDL for Postgres and YugabyteDB to just create a default partition table
  ebean-api/src/main/java/io/ebean/config/dbplatform/DatabasePlatform.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/DdlGenerator.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PostgresDdl.java
  ebean-ddl-generator/src/test/java/io/ebeaninternal/dbmigration/PostgresPlatformTest.java
  platforms/postgres/src/main/java/io/ebean/platform/postgres/PostgresPlatform.java
  platforms/postgres/src/test/java/io/ebean/platform/postgres/PostgresPlatformTest.java
Labels: refactor
