Repository ebean-orm/ebean, pull requests merged in 2022-10, with the labels that each got.

#2826 Refactor extract ebean-jackson-jsonnode module - support for Jackson JsonNode (into separate module)
  composites/ebean/pom.xml
  ebean-bom/pom.xml
  ebean-core-type/pom.xml
  ebean-core-type/src/main/java/io/ebean/core/type/PostgresHelper.java
  ebean-core-type/src/main/java/io/ebean/core/type/ScalarTypeSet.java
  ebean-core-type/src/main/java/io/ebean/core/type/ScalarTypeSetFactory.java
  ebean-core-type/src/main/java/module-info.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationAssocManys.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationBase.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationFields.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/DeployCreateProperties.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/DeployUtil.java
  ebean-core/src/main/java/io/ebeaninternal/server/dto/DtoMetaConstructor.java
  ebean-core/src/main/java/io/ebeaninternal/server/dto/DtoMetaProperty.java
  ebean-core/src/main/java/io/ebeaninternal/server/json/DJsonScalar.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/Binder.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/DefaultTypeManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeCidr.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeInet.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeInetAddressPostgres.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonList.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonMapPostgres.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonSet.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonString.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/TypeJsonManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/TypeManager.java
  ebean-core/src/main/java/module-info.java
  ebean-core/src/test/java/io/ebeaninternal/server/type/DefaultTypeManagerTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/type/TestTypeManager.java
  ebean-jackson-jsonnode/pom.xml
  ebean-jackson-jsonnode/src/main/java/io/ebean/jackson/jsonnode/JsonNodeSet.java
  ebean-jackson-jsonnode/src/main/java/io/ebean/jackson/jsonnode/JsonNodeTypeFactory.java
  ebean-jackson-jsonnode/src/main/java/io/ebean/jackson/jsonnode/ScalarTypeJsonNode.java
  ebean-jackson-jsonnode/src/main/java/io/ebean/jackson/jsonnode/ScalarTypeJsonNodePostgres.java
  ebean-jackson-jsonnode/src/main/java/module-info.java
  ebean-jackson-jsonnode/src/main/resources/META-INF/services/io.ebean.core.type.ScalarTypeSetFactory
  ebean-test/pom.xml
  pom.xml
Labels: dependencies, reason-for-version-bump

#2859 Possible memory leak with BackgroundExecutor using BackgroundExecutorWrapper ThreadLocals (for scheduled tasks)
  ebean-api/src/main/java/io/ebean/config/BackgroundExecutorWrapper.java
  ebean-core/src/main/java/io/ebeaninternal/server/executor/DefaultBackgroundExecutor.java
Labels: bug, behaviour change

#2863 FIX: LogFormat for SystemLogger
  ebean-core/src/main/java/io/ebeaninternal/server/idgen/UuidV1RndIdGenerator.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/extraddl/model/ExtraDdlXmlReader.java
Labels: bug

#2867 FIX: Flush transaction if it is modified in callback
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/JdbcTransaction.java
  ebean-test/src/test/java/io/ebean/xtest/internal/server/transaction/JdbcTransactionTest.java
Labels: bug

#2868 FIX: toJsonNanos for calendar
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeCalendar.java
Labels: bug

#2869 FIX: Add fallback for Ebean 11 Jsons
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeLocalDateTime.java
  ebean-core/src/test/java/io/ebeaninternal/server/type/ScalarTypeLocalDateTimeTest.java
Labels: bug
