Repository ebean-orm/ebean, pull requests merged in 2022-03, with the labels that each got.

#2583 #2582 - Fix for regression, BackgroundExecutor is bounded (since 12.6.2)
  ebean-core/src/main/java/io/ebeaninternal/server/executor/DaemonExecutorService.java
  ebean-core/src/main/java/io/ebeaninternal/server/executor/DefaultBackgroundExecutor.java
  ebean-core/src/test/java/io/ebeaninternal/server/executor/DaemonExecutorServiceTest.java
Labels: bug, behaviour change

#2580 Bug: Wrong join in query with @Inheritance and @DbForeignKey
  ebean-test/src/test/java/org/tests/model/join/Access.java
  ebean-test/src/test/java/org/tests/model/join/Account.java
  ebean-test/src/test/java/org/tests/model/join/AccountAccess.java
  ebean-test/src/test/java/org/tests/model/join/BankAccount.java
  ebean-test/src/test/java/org/tests/model/join/CustomerAccess.java
  ebean-test/src/test/java/org/tests/query/TestQueryMultiJoinFetchPath.java
Labels: bug

#2596 DDl-Refactor: Add DB2 Reorg support and history support
  ebean-api/src/main/java/io/ebean/config/dbplatform/db2/BaseDB2Platform.java
  ebean-api/src/main/java/io/ebean/config/dbplatform/db2/DB2HistorySupport.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/DB2Ddl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/Db2HistoryDdl.java
  ebean-ddl-generator/src/test/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl_AlterColumnTest.java
  ebean-test/src/test/java/io/ebeaninternal/dbmigration/DbMigrationTest.java
  ebean-test/src/test/java/org/tests/model/history/TestHistoryExclude.java
  ebean-test/src/test/java/org/tests/model/history/TestHistoryInclude.java
  ebean-test/src/test/java/org/tests/model/history/TestHistoryOneToMany.java
  ebean-test/src/test/java/org/tests/query/finder/TestCustomerFinder.java
  ebean-test/src/test/resources/migrationtest/dbmigration/db2fori/1.0__initial.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2fori/1.1.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2fori/1.2__dropsFor_1.1.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2fori/1.3.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2fori/1.4__dropsFor_1.3.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2fori/idx_db2.migrations
  ebean-test/src/test/resources/migrationtest/dbmigration/db2legacy/1.0__initial.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2legacy/1.1.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2legacy/1.2__dropsFor_1.1.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2legacy/1.3.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2legacy/1.4__dropsFor_1.3.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2legacy/idx_db2.migrations
  ebean-test/src/test/resources/migrationtest/dbmigration/db2luw/1.0__initial.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2luw/1.1.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2luw/1.2__dropsFor_1.1.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2luw/1.3.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2luw/1.4__dropsFor_1.3.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2luw/idx_db2.migrations
  ebean-test/src/test/resources/migrationtest/dbmigration/db2zos/1.0__initial.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2zos/1.1.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2zos/1.2__dropsFor_1.1.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2zos/1.3.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2zos/1.4__dropsFor_1.3.sql
  ebean-test/src/test/resources/migrationtest/dbmigration/db2zos/idx_db2.migrations
Labels: refactor

#2604 Remove LowerTableName
  ebean-api/src/main/java/io/ebean/config/DbConstraintNaming.java
  ebean-api/src/main/java/io/ebean/config/DbConstraintNormalise.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/DB2Ddl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/Db2HistoryDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/DbTriggerBasedHistoryDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/HanaHistoryDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PlatformDdl.java
  ebean-ddl-generator/src/test/resources/assert/ModelBuild_explicitSequencesTest/apply.sql
  ebean-ddl-generator/src/test/resources/assert/ModelBuild_explicitSequencesTest/pg-apply.sql
  ebean-test/src/test/java/io/ebean/config/DbConstraintNamingTest.java
Labels: refactor

#2617 ENH: JsonContext accepts a bean as target
  ebean-api/src/main/java/io/ebean/text/json/JsonBeanReader.java
  ebean-api/src/main/java/io/ebean/text/json/JsonContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorElementEmbedded.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorElementEmbeddedMap.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorJsonHelp.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocMany.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocOne.java
  ebean-core/src/main/java/io/ebeaninternal/server/text/json/DJsonBeanReader.java
  ebean-core/src/main/java/io/ebeaninternal/server/text/json/DJsonContext.java
  ebean-test/src/test/java/org/tests/text/json/TestJsonBeanDescriptorParse.java
Labels: enhancement

#2624 #2623 - CurrentTenantProvider called even when table has no tenantId column specified
  ebean-core/src/main/java/io/ebeaninternal/server/core/MultiTenantDbCatalogSupplier.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/MultiTenantDbSchemaSupplier.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/MultiTenantDbSupplier.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/SimpleDataSourceProvider.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/DataSourceSupplier.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/TransactionFactoryTenantWithRead.java
  ebean-test/src/test/java/org/multitenant/partition/CurrentTenant.java
  ebean-test/src/test/java/org/multitenant/partition/MtNone.java
  ebean-test/src/test/java/org/multitenant/partition/MultiTenantPartitionTest.java
Labels: bug
