Repository ebean-orm/ebean, pull requests merged in 2022-01, with the labels that each got.

#2485 Fix utf8 problems with specialchars
  ebean-api/src/main/java/io/ebean/text/csv/CsvReader.java
  ebean-api/src/main/java/io/ebean/util/IOUtils.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DScriptRunner.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/DefaultProfileHandler.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonMap.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeJsonNode.java
  ebean-core/src/main/java/io/ebeaninternal/server/type/SimpleAesEncryptor.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/DdlGenerator.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/DefaultDbMigration.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/IndexMigration.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/MChecksum.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/migrationreader/MigrationXmlWriter.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/model/PlatformDdlWriter.java
  ebean-ddl-generator/src/test/java/io/ebeaninternal/dbmigration/MChecksumTest.java
  ebean-ddl-generator/src/test/java/io/ebeaninternal/dbmigration/ddlgeneration/Helper.java
  ebean-ddl-generator/src/test/resources/dbmigration/index-special-chars/1.0__hello.sql
  ebean-test/src/test/java/io/ebean/json/EJsonTests.java
  ebean-test/src/test/java/io/ebeaninternal/server/cache/CachedBeanDataSerializeTest.java
  ebean-test/src/test/java/io/ebeaninternal/server/type/TestSimpleEncryptor.java
  ebean-test/src/test/java/org/tests/basic/TestDeleteImportedPartial.java
  ebean-test/src/test/java/org/tests/basic/TestDeleteOneToOne.java
  ebean-test/src/test/java/org/tests/basic/TestDeleteOneToOneMultiple.java
  ebean-test/src/test/java/org/tests/basic/TestSaveDeleteOneToOne.java
  ebean-test/src/test/java/org/tests/basic/TestSaveDeleteOneToOneMultiple.java
  ebean-test/src/test/java/org/tests/enhancement/TestConstructorPutfieldReplacement.java
  ebean-test/src/test/java/org/tests/text/csv/TestCsvReader.java
  ebean-test/src/test/java/org/tests/text/csv/TestCsvReaderWithCallback.java
  ebean-test/src/test/java/org/tests/text/json/TestJsonSimple.java
Labels: bug

#2502 Fix: composite id in select distinct queries
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryBuilder.java
  ebean-test/src/test/java/org/tests/compositekeys/TestOnCascadeDeleteChildrenWithCompositeKeys.java
Labels: bug

#2504 Cannot delete bean with more than 2100 child beans on SqlServer
  ebean-core/src/main/java/io/ebeaninternal/server/persist/DefaultPersister.java
  ebean-test/src/test/java/org/tests/delete/TestDeleteByQuery.java
Labels: bug

#2505 Refactor UUID generator. Add uuid-property to serverConfig (#57)
  ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/idgen/UuidV1IdGenerator.java
  ebean-test/src/test/java/io/ebeaninternal/server/idgen/TestUuidGenerator.java
Labels: refactor

#2512 ADD: different DB2 platforms
  .github/workflows/multi-platform-test.yml
  ebean-api/pom.xml
  ebean-api/src/main/java/io/ebean/config/dbplatform/db2/BaseDB2Platform.java
  ebean-api/src/main/java/io/ebean/config/dbplatform/db2/DB2ForIPlatform.java
  ebean-api/src/main/java/io/ebean/config/dbplatform/db2/DB2LegacyPlatform.java
  ebean-api/src/main/java/io/ebean/config/dbplatform/db2/DB2LuwPlatform.java
  ebean-api/src/main/java/io/ebean/config/dbplatform/db2/DB2ZosPlatform.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DatabasePlatformFactory.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/DefaultDbMigration.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/PlatformDdlBuilder.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/DB2Ddl.java
  ebean-ddl-generator/src/test/resources/dbmigration/migrationtest/db2/1.1.sql
  ebean-ddl-generator/src/test/resources/dbmigration/migrationtest/db2/1.3.sql
  ebean-ddl-generator/src/test/resources/dbmigration/migrationtest/db2/idx_db2.migrations
  ebean-test/testconfig/ebean-db2.properties
Labels: refactor, behaviour change, reason-for-version-bump

#2509 Support jedis 4.1.0 client (ScanParams, ScanResult in different package now)
  ebean-redis/pom.xml
  ebean-redis/src/main/java/io/ebean/redis/RedisCache.java
Labels: dependencies, reason-for-version-bump

#2516 Yugabyte platform support - Automatic detection and DDL support
  ebean-api/pom.xml
  ebean-api/src/main/java/io/ebean/config/dbplatform/yugabyte/YugabytePlaform.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DatabasePlatformFactory.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/platform/DbExpressionHandlerFactory.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/PlatformDdlBuilder.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/DbTriggerBasedHistoryDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/PostgresHistoryDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/YugabyteDdl.java
  ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/YugabyteHistoryDdl.java
  ebean-test/pom.xml
  ebean-test/src/test/java/main/StartYugabyte.java
  ebean-test/src/test/resources/ebean.properties
Labels: enhancement

#2526 DB2: Do not try to update deferred null values (Discovered by TestPrinterStateIssue)
  ebean-core/src/main/java/io/ebeaninternal/api/BindParams.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistDeferredRelationship.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/id/ImportedIdEmbedded.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/id/ImportedIdSimple.java
Labels: behaviour change
