Repository ebean-orm/ebean, pull requests merged in 2023-02, with the labels that each got.

#2941 NEW: ExpressionList has clear() method
  ebean-api/src/main/java/io/ebean/ExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  ebean-core/src/test/java/io/ebeaninternal/server/expression/DefaultExpressionListTest.java
Labels: enhancement

#2936 BUG: Memory-leak on streaming queries when LoadBuffers are not aligned
  ebean-core/src/main/java/io/ebeaninternal/api/LoadContext.java
  ebean-core/src/main/java/io/ebeaninternal/api/LoadManyBuffer.java
  ebean-core/src/main/java/io/ebeaninternal/api/LoadManyRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/OrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadManyContext.java
  ebean-test/src/test/java/org/tests/basic/TestPersistenceContextMany.java
Labels: bug

#2912 Refactoring SpiLogger to better support conditional logging
  ebean-core/src/main/java/io/ebeaninternal/api/SpiLogManager.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiLogger.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiTransactionProxy.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiTxnLogger.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/AbstractSqlQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/OrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequestBean.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequestCallableSql.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequestOrmUpdate.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequestUpdateSql.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/RelationalQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/logger/DLogManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/logger/DSpiLogger.java
  ebean-core/src/main/java/io/ebeaninternal/server/logger/DTxnLogger.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/BatchControl.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/Binder.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/DefaultPersister.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/DeleteUnloadedForeignKeys.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dml/DmlHandler.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/DocStoreOnlyTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/DocStoreTransactionManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/ExternalJdbcTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/ImplicitReadOnlyTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/JdbcTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/JtaTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/JtaTransactionManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/NoTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/SavepointTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/TransactionFactory.java
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/TransactionManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/util/Str.java
  ebean-test/src/main/java/io/ebean/test/CaptureLogger.java
  ebean-test/src/main/java/io/ebean/test/CapturingLoggerFactory.java
  ebean-test/src/test/java/io/ebean/xtest/base/EbeanServerFactory_ServerConfigStart_Test.java
  ebean-test/src/test/java/io/ebean/xtest/internal/server/transaction/TransactionManagerTest.java
Labels: refactor

#2969 #2968 - [ebean-test] - Default ebean.test.registerTestTenantProvider = false ... by default not auto register a test TenantProvider
  ebean-test/src/main/java/io/ebean/test/config/provider/ProviderAutoConfig.java
Labels: reason-for-version-bump

#2979 ENH: Add _ifPresent() expressions for GT, GE, LT, LE (follow up from #2768)
  ebean-api/src/main/java/io/ebean/ExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  ebean-querybean/src/main/java/io/ebean/typequery/PBaseComparable.java
  ebean-querybean/src/test/java/org/querytest/MyInnerTest.java
  ebean-test/src/test/java/org/tests/query/TestQueryIsNull.java
Labels: enhancement

#2983 ENH: Add profile-line-number-mode with options none | all | auto ... to control adding line numbers to profile locations
  ebean-api/src/main/java/io/ebean/ProfileLocation.java
  ebean-api/src/main/java/io/ebean/service/SpiProfileLocationFactory.java
  ebean-api/src/main/resources/META-INF/ebean-version.mf
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DProfileLocation.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DProfileLocationFactory.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/DTimedProfileLocation.java
  ebean-core/src/main/java/io/ebeaninternal/server/profile/UtilLocation.java
  ebean-core/src/test/java/io/ebeaninternal/server/profile/BasicProfileLocationTest.java
  ebean-core/src/test/java/io/ebeaninternal/server/profile/UtilLocationTest.java
  ebean-externalmapping-xml/src/test/resources/META-INF/ebean-version.mf
  ebean-querybean/pom.xml
  ebean-querybean/src/test/java/org/querytest/QContactTest.java
  ebean-querybean/src/test/java/org/querytest/QCustomerTest.java
  ebean-querybean/src/test/resources/application-test.properties
  ebean-querybean/src/test/resources/ebean.mf
  ebean-test/src/test/java/org/tests/profile/ProfileLocationTest.java
  kotlin-querybean-generator/src/test/resources/META-INF/ebean-version.mf
  pom.xml
  tests/test-kotlin/src/test/resources/META-INF/ebean-version.mf
Labels: enhancement

#2980 FIX: do not format log messages, when no parameter was specified
  ebean-test/src/main/java/io/ebean/test/CaptureLogger.java
  ebean-test/src/test/java/io/ebean/test/TestCaptureLogger.java
  ebean-test/src/test/resources/logback-test.xml
Labels: bug

#2986 [querybeans] Add support for using interface types with querybean expressions eq() in() etc WHEN entity beans implement an interface
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/Constants.java
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/ProcessingContext.java
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/SimpleQueryBeanWriter.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/Constants.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/ProcessingContext.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/SimpleQueryBeanWriter.java
  tests/test-kotlin/pom.xml
  tests/test-kotlin/src/test/kotlin/org/example/api/ICustomer.kt
  tests/test-kotlin/src/test/kotlin/org/example/order/Customer.kt
Labels: enhancement

#2987 [QueryBeans] Refactor splitting TQAssocBean into TQAssoc & TQAssocBean
  ebean-querybean/pom.xml
  ebean-querybean/src/main/java/io/ebean/typequery/TQAssoc.java
  ebean-querybean/src/main/java/io/ebean/typequery/TQAssocBean.java
  kotlin-querybean-generator/pom.xml
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/Constants.java
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/KotlinLangAdapter.java
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/SimpleQueryBeanWriter.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/Constants.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/SimpleQueryBeanWriter.java
  tests/test-java16/pom.xml
Labels: refactor, reason-for-version-bump

#2988 [QueryBeans] Fix for missing inherited properties when parent only has @DiscriminatorValue
  ebean-querybean/src/test/java/org/example/domain/ACat.java
  ebean-querybean/src/test/java/org/example/domain/ASuperCat.java
  ebean-querybean/src/test/java/org/querytest/InheritanceTest.java
  ebean-querybean/src/test/java/org/querytest/QCustomerTest.java
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/Constants.java
  kotlin-querybean-generator/src/main/java/io/ebean/querybean/generator/ProcessingContext.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/Constants.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/ProcessingContext.java
  tests/test-java16/pom.xml
Labels: bug
