Repository ebean-orm/ebean, pull requests merged in 2023-03, with the labels that each got.

#2995 Change such that querybean generated class registration can be used with explicit class registration
  ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java
  ebean-api/src/test/java/io/ebean/config/DatabaseConfigTest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultContainer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/bootup/BootupClasses.java
  ebean-core/src/test/java/io/ebeaninternal/server/deploy/BeanDescriptor_registerTest.java
  ebean-test/src/test/java/io/ebean/xtest/config/PlatformNoGeneratedKeysTest.java
  ebean-test/src/test/java/io/ebean/xtest/config/ServerConfigSqlServerTest.java
  ebean-test/src/test/java/io/ebean/xtest/event/BeanFindControllerTest.java
  ebean-test/src/test/java/io/ebean/xtest/event/BeanPersistControllerTest.java
  ebean-test/src/test/java/io/ebean/xtest/event/BeanPostLoadTest.java
  ebean-test/src/test/java/io/ebean/xtest/internal/server/transaction/DefaultTransactionThreadLocalTest.java
  ebean-test/src/test/java/org/multitenant/partition/MultiTenantPartitionTest.java
Labels: behaviour change, reason-for-version-bump

#2996 Add support for specifying select clause with RawSql
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryBuilderRawSql.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/rawsql/DRawSql.java
  ebean-core/src/main/java/io/ebeaninternal/server/rawsql/SpiRawSql.java
  ebean-test/src/test/java/org/tests/rawsql/TestRawSqlOrmQuery.java
  ebean-test/src/test/java/org/tests/rawsql/TestRawSqlQuerySelect.java
  ebean-test/src/test/java/org/tests/rawsql/transport/QuerySumResponse.java
  ebean-test/src/test/java/org/tests/rawsql/transport/SampleReport.java
Labels: enhancement, behaviour change, reason-for-version-bump

#2999 #2998 - SQLServer, map java long to BIGINT for bitwise expressions
  ebean-test/src/test/java/org/tests/expression/bitwise/BwBean.java
  ebean-test/src/test/java/org/tests/rawsql/TestRawSqlQuerySelect.java
  platforms/sqlserver/src/main/java/io/ebean/platform/sqlserver/SqlServerBasePlatform.java
Labels: bug

#3000 FIX: DB.json().toBean(target) can update existing lists (#85)
  ebean-core/src/main/java/io/ebeaninternal/api/json/SpiJsonReader.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorJsonHelp.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanProperty.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocMany.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocManyJsonHelp.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocOne.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertySimpleCollection.java
  ebean-core/src/main/java/io/ebeaninternal/server/json/ReadJson.java
  ebean-test/src/test/java/org/tests/text/json/TestJsonBeanDescriptorParse.java
Labels: bug

#3007 Refactor rename methods in LoadContext
  ebean-api/src/main/java/io/ebean/bean/BeanLoader.java
  ebean-api/src/main/java/io/ebean/bean/InterceptReadWrite.java
  ebean-api/src/main/java/io/ebean/bean/SingleBeanLoader.java
  ebean-core/src/main/java/io/ebeaninternal/api/LoadContext.java
  ebean-core/src/main/java/io/ebeaninternal/api/LoadManyBuffer.java
  ebean-core/src/main/java/io/ebeaninternal/api/LoadManyRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/OrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadBaseContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadBeanContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/loadcontext/DLoadManyContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQuery.java
Labels: refactor
