Repository ebean-orm/ebean, pull requests merged in 2023-08, with the labels that each got.

#3154 #3134 - String cannot be cast to class io.ebean.bean.EntityBean" when deleting entities that use cascade = [CascadeType.ALL] with composite keys
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorElement.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/id/IdBinder.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/id/IdBinderEmbedded.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/id/IdBinderEmpty.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/id/IdBinderSimple.java
  ebean-test/src/test/java/org/tests/cache/embeddedid/Concept.java
  ebean-test/src/test/java/org/tests/cache/embeddedid/ConceptId.java
  ebean-test/src/test/java/org/tests/cache/embeddedid/Connection.java
  ebean-test/src/test/java/org/tests/cache/embeddedid/TestCompositeForeignKey.java
Labels: bug

#3155 #3133 - For IdClass match on property name
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/visitor/VisitProperties.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dmlbind/BindableIdEmbedded.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dmlbind/MatchedImportedEmbedded.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dmlbind/MatchedImportedFactory.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dmlbind/MatchedImportedProperty.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dmlbind/MatchedImportedScalar.java
  ebean-test/src/test/java/org/tests/cache/embeddedid/Concept2.java
  ebean-test/src/test/java/org/tests/cache/embeddedid/TestCompositeForeignKey.java
Labels: bug

#3145 FIX: Query on formula m2o-property uses wrong alias:
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanProperty.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocOne.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/DbSqlContext.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultDbSqlContext.java
  ebean-test/src/test/java/org/tests/model/basic/TreeNode.java
  ebean-test/src/test/java/org/tests/query/joins/TestQueryJoinOnFormula.java
Labels: bug

#3148 FIX: Recursive batch flush can save beans in wrong order
  ebean-core/src/main/java/io/ebeaninternal/server/persist/BatchControl.java
  ebean-test/src/test/java/org/tests/batchinsert/TestBatchInsertFlush.java
  ebean-test/src/test/java/org/tests/model/basic/event/CustomerPersistAdapter.java
Labels: bug

#3147 FIX: Rethrow error in commit path of callbacks
  ebean-core/src/main/java/io/ebeaninternal/server/transaction/JdbcTransaction.java
Labels: bug

#3169 Add Query bean filterMany() taking a closure
  ebean-api/src/main/java/io/ebean/ExpressionFactory.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionFactory.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-querybean/pom.xml
  ebean-querybean/src/main/java/io/ebean/typequery/TQRootBean.java
  ebean-querybean/src/test/java/org/querytest/QCustomerTest.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/Constants.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/ProcessingContext.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/Processor.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/PropertyMeta.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/PropertyTypeAssoc.java
  querybean-generator/src/main/java/io/ebean/querybean/generator/SimpleQueryBeanWriter.java
Labels: reason-for-version-bump

#3171 FIX for filterMany with raw expression with single SQL query
  ebean-core/src/main/java/io/ebeaninternal/server/expression/RawExpression.java
  ebean-core/src/test/java/io/ebeaninternal/server/expression/RawExpressionTest.java
  ebean-test/src/test/java/org/tests/query/TestQueryFilterMany.java
Labels: bug

#3172 Add filterManyRaw() and Deprecate filterMany( <string expressions> )
  ebean-api/src/main/java/io/ebean/ExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  ebean-querybean/src/main/java/io/ebean/typequery/TQAssocBean.java
  ebean-querybean/src/test/java/org/querytest/QCustomerTest.java
  ebean-test/src/test/java/org/tests/query/TestQueryFilterMany.java
Labels: deprecated-api

#3180 BUG: Using a subquery with idEq or setId is missing the bind value
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryPredicates.java
  ebean-test/src/test/java/org/tests/query/TestQuerySubquery.java
Labels: bug

#3179 Experimental elliminate not in with too many params
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssoc.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocMany.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocManySqlHelp.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanPropertyAssocOne.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/IntersectionRow.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/DefaultPersister.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/SaveManyBase.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/SaveManyBeans.java
  ebean-test/src/test/java/org/tests/cascade/TestOrphanCollectionReplacement.java
  ebean-test/src/test/java/org/tests/compositekeys/TestOnCascadeDeleteChildrenWithCompositeKeys.java
Labels: bug, refactor

#3186 #3183 - Fix for: Wrong limit using setMaxRows on delete between calls
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryPlanKey.java
  ebean-test/src/test/java/org/tests/delete/TestDeleteByQuery.java
Labels: bug

#3191 #3188 Fix findFutureCount() when there is a current transaction in scope
  ebean-core/src/main/java/io/ebeaninternal/api/SpiEbeanServer.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CallableQueryCount.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CallableQueryIds.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CallableQueryList.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/LimitOffsetPagedList.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiEbeanServer.java
  ebean-test/src/test/java/org/tests/query/TestFindFutureRowCount.java
Labels: bug

#3195 Deprecate for removal Database.commitTransaction() and Database.rollb…
  ebean-api/src/main/java/io/ebean/DB.java
  ebean-api/src/main/java/io/ebean/Database.java
  ebean-api/src/main/java/io/ebean/ExpressionList.java
  ebean-api/src/main/java/io/ebean/Query.java
  ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/BeanRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/ObtainedTransactionImplicit.java
Labels: deprecated-api

#3198 [15x] Remove Named queries, ANTLR, Query language parser
  ebean-api/src/main/java/io/ebean/BeanFinder.java
  ebean-api/src/main/java/io/ebean/DB.java
  ebean-api/src/main/java/io/ebean/Database.java
  ebean-api/src/main/java/io/ebean/ExpressionFactory.java
  ebean-api/src/main/java/io/ebean/ExpressionList.java
  ebean-api/src/main/java/io/ebean/Finder.java
  ebean-core/pom.xml
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionFactory.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/EqlAdapter.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/EqlOperator.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/EqlParser.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/EqlValueType.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/EqlWhereAdapter.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/EqlWhereListener.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/NamedParameter.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/OperatorMapping.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQL.interp
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQL.tokens
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQLBaseListener.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQLBaseVisitor.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQLLexer.interp
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQLLexer.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQLLexer.tokens
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQLListener.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQLParser.java
  ebean-core/src/main/java/io/ebeaninternal/server/grammer/antlr/EQLVisitor.java
  ebean-core/src/main/java/module-info.java
  ebean-querybean/src/main/java/io/ebean/typequery/TQAssocBean.java
  ebean-querybean/src/test/java/org/querytest/QCustomerTest.java
  ebean-test/src/test/java/io/ebean/xtest/base/EbeanServer_eqlTest.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiEbeanServer.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiServer.java
  ebean-test/src/test/java/io/ebean/xtest/internal/server/grammer/EqlParserTest.java
  ebean-test/src/test/java/org/tests/model/basic/finder/CustomerFinder.java
  ebean-test/src/test/java/org/tests/query/TestQueryFilterMany.java
Labels: Ebean 15.x

#3199 [15x] Remove Named DTO queries and External Mapping (loading named queries)
  ebean-api/src/main/java/io/ebean/Database.java
  ebean-core/pom.xml
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/InternalConfigXmlMap.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/InternalConfiguration.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/meta/DeployBeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationClass.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/DeployBeanInfo.java
  ebean-core/src/main/java/io/ebeaninternal/server/dto/DtoBeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/dto/DtoBeanManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/dto/DtoNamedQueries.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-core/src/main/java/module-info.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiEbeanServer.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiServer.java
Labels: Ebean 15.x

#3203 #3173 - BeanSet lazy loading / Too many DataSource connections used
  ebean-api/src/main/java/io/ebean/common/BeanSet.java
  ebean-test/src/test/java/org/tests/sets/M2MDepart.java
  ebean-test/src/test/java/org/tests/sets/M2MEmp.java
  ebean-test/src/test/java/org/tests/sets/TestM2MSet.java
Labels: bug

#3205 Follow up #3173 - Change BeanSet clear() to lazy load ALL properties
  ebean-api/src/main/java/io/ebean/common/BeanSet.java
  ebean-test/src/test/java/org/tests/sets/TestO2MSet.java
Labels: behaviour change

#3206 Map.clear() on a @OneToMany orphanRemoval=true invokes 1+N queries du…
  ebean-core/src/main/java/io/ebeaninternal/api/LoadManyRequest.java
  ebean-test/src/test/java/org/tests/sets/TestO2MMap.java
Labels: bug
