Repository ebean-orm/ebean, pull requests merged in 2024-02, with the labels that each got.

#3310 Previous entities are not deleted when replacing OneToMany collection with a new one
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequestBean.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/SaveManyBeans.java
  ebean-test/src/test/java/org/tests/model/orphanremoval/OmBeanListParent.java
  ebean-test/src/test/java/org/tests/o2m/OneToManyListMarkAsDirtyTest.java
Labels: bug

#3324 Add support for Postgres INSERT ON CONFLICT update | nothing
  ebean-api/src/main/java/io/ebean/DInsertOptionsBuilder.java
  ebean-api/src/main/java/io/ebean/Database.java
  ebean-api/src/main/java/io/ebean/InsertOptions.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequestBean.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/Persister.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/DefaultPersister.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dml/GenerateDmlRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dml/InsertHandler.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dml/InsertMeta.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dml/InsertMetaOptions.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dml/InsertMetaOptionsPostgres.java
  ebean-core/src/main/java/io/ebeaninternal/server/persist/dml/InsertMetaPlatform.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiServer.java
  ebean-test/src/test/java/org/tests/insert/TestInsertOnConflict.java
Labels: enhancement

#3322 (fix) Future queries do not trigger flush on BatchedPstmtHolder for #3319
  ebean-core/src/main/java/io/ebeaninternal/api/SpiQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultOrmQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-test/src/test/java/org/tests/query/TestFindFutureRowCount.java
Labels: bug, behaviour change

#3327 Remove deprecated database.commitTransaction(), migrate to transaction.commit()
  ebean-api/src/main/java/io/ebean/DB.java
  ebean-api/src/main/java/io/ebean/Database.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiEbeanServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-test/src/test/java/io/ebean/xtest/base/TransactionalTestCase.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiEbeanServer.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiServer.java
  ebean-test/src/test/java/io/ebean/xtest/internal/server/transaction/DefaultTransactionThreadLocalTest.java
  ebean-test/src/test/java/org/tests/basic/TestDynamicUpdate.java
  ebean-test/src/test/java/org/tests/basic/TestInheritRef.java
  ebean-test/src/test/java/org/tests/basic/TestPersistenceContext.java
  ebean-test/src/test/java/org/tests/cache/TestCacheInterceptSaveWhenLazyLoaded.java
  ebean-test/src/test/java/org/tests/genkey/TestGeneratedKeys.java
  ebean-test/src/test/java/org/tests/level/test/ManyToManyTest.java
  ebean-test/src/test/java/org/tests/model/basic/xtra/TestDeleteUnloadedChildren.java
  ebean-test/src/test/java/org/tests/model/basic/xtra/TestInsertBatchThenFlushThenUpdate.java
  ebean-test/src/test/java/org/tests/model/basic/xtra/TestInsertBatchThenUpdate.java
  ebean-test/src/test/java/org/tests/model/basic/xtra/TestInsertBatchWithDifferentRootTypes.java
  ebean-test/src/test/java/org/tests/persistencecontext/TestPersistenceContextOnUpdateDuringTxn.java
  ebean-test/src/test/java/org/tests/persistencecontext/TestPersistenceContextQueryScope.java
  ebean-test/src/test/java/org/tests/query/TestConnectionCloseOnSqlerr.java
  ebean-test/src/test/java/org/tests/query/TestQueryFindPagedList.java
  ebean-test/src/test/java/org/tests/query/finder/TestCustomerFinder.java
  ebean-test/src/test/java/org/tests/query/joins/TestDisjunctWhereOuterJoin.java
  ebean-test/src/test/java/org/tests/query/other/TestManyLazyLoadingQuery.java
  ebean-test/src/test/java/org/tests/transaction/TestBatchPersistCascade.java
  ebean-test/src/test/java/org/tests/transaction/TestDeleteFromPersistenceContext.java
  ebean-test/src/test/java/org/tests/transaction/TestNestedSubTransaction.java
  ebean-test/src/test/java/org/tests/transaction/TestStatelessUpdateClearPC.java
  ebean-test/src/test/java/org/tests/transaction/TestTransactionCallback.java
  ebean-test/src/test/java/org/tests/transaction/TestTransactionalNotSupports.java
  ebean-test/src/test/java/org/tests/transaction/TestTransactionalRequired.java
  ebean-test/src/test/java/org/tests/transaction/TestTransactionalRequiresNew.java
  ebean-test/src/test/java/org/tests/transaction/TestTransactionalSupports.java
  ebean-test/src/test/java/org/tests/update/TestSqlUpdateInTxn.java
Labels: deprecated-api, removed-api

#3301 #3295 Clear PersistenceContext on execution of bulk updates or deletes
  ebean-core/src/main/java/io/ebeaninternal/server/core/OrmQueryRequest.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequestOrmUpdate.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/PersistRequestUpdateSql.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptor.java
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryEngine.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryUpdate.java
  ebean-test/src/test/java/org/tests/persistencecontext/TestPersistenceContextQueryScope.java
Labels: behaviour change

#3289 Change semantic of userObjects in nested transaction
  ebean-core/src/main/java/io/ebeaninternal/api/ScopeTrans.java
  ebean-core/src/main/java/io/ebeaninternal/api/ScopedTransaction.java
  ebean-core/src/main/java/io/ebeaninternal/server/util/ArrayStack.java
  ebean-test/src/test/java/org/tests/transaction/TestExecuteComplete.java
Labels: behaviour change, reason-for-version-bump

#3339 Fix for #3338 Potential shutdown hang with SpringContextShutdownHook …
  ebean-api/src/main/java/io/ebean/event/ShutdownManager.java
Labels: bug

#3340 Revert "[15x] Remove "Future queries" findFutureList, findFutureIds, findFutureCount"
  ebean-api/src/main/java/io/ebean/ExpressionList.java
  ebean-api/src/main/java/io/ebean/FutureIds.java
  ebean-api/src/main/java/io/ebean/Query.java
  ebean-core/src/main/java/io/ebeaninternal/api/SpiEbeanServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/DefaultExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/FilterExpressionList.java
  ebean-core/src/main/java/io/ebeaninternal/server/expression/JunctionExpression.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/DefaultFetchGroupQuery.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/QueryFutureIds.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/QueryFutureList.java
  ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java
  ebean-querybean/src/main/java/io/ebean/typequery/TQRootBean.java
  ebean-test/src/test/java/io/ebean/xtest/internal/api/TDSpiEbeanServer.java
  ebean-test/src/test/java/io/ebean/xtest/internal/server/query/TestFutureRowCountErrorHandling.java
  ebean-test/src/test/java/org/tests/basic/TestFetchId.java
  ebean-test/src/test/java/org/tests/query/TestFindFutureRowCount.java
  ebean-test/src/test/java/org/tests/query/TestQueryFindFutureList.java
  ebean-test/src/test/java/org/tests/query/cancel/SqlQueryCancelTest.java
  ebean-test/src/test/java/org/tests/rawsql/TestRawSqlOrmQuery.java
Labels: Ebean 15.x
