Repository ebean-orm/ebean, pull requests merged in 2024-10, with the labels that each got.

#3493 #3490 filterMany generates invalid sql when the many side uses @EmbeddedId to model composite primary key
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/id/IdBinderEmbedded.java
  ebean-querybean/src/test/java/org/example/domain/DataWithFormula.java
  ebean-querybean/src/test/java/org/example/domain/DataWithFormulaKey.java
  ebean-querybean/src/test/java/org/example/domain/DataWithFormulaMain.java
  ebean-querybean/src/test/java/org/querytest/QDataWithFormulaMainTest.java
Labels: bug

#3485 Fix orderBy for cached many requests
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultBeanLoader.java
  ebean-test/src/test/java/org/tests/cascade/TestOrderedList.java
Labels: bug

#3487 Bug: Batch ordering - Regression introduced in version 13.26.1, insertAll() leaves batchMode=true enabled ... when it should not
  ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java
  ebean-test/src/test/java/org/tests/batchinsert/TestBatchInsertFlush.java
Labels: bug, regression

#3499 Potentially breaking change: Throw PersistenceException for unknown property in select clause
  ebean-core/src/main/java/io/ebeaninternal/server/query/SqlTreeBuilder.java
  ebean-test/src/test/java/io/ebean/xtest/internal/server/text/json/WriteJsonTest.java
  ebean-test/src/test/java/org/tests/basic/TestMappedSuper.java
  ebean-test/src/test/java/org/tests/model/noid/TestInsertNoIdBean.java
  ebean-test/src/test/java/org/tests/query/TestInvalidFetchPath.java
  ebean-test/src/test/java/org/tests/types/TestFileType.java
  ebean-test/src/test/java/org/tests/types/TestFileTypeFetching.java
Labels: behaviour change

#3504 Fix: dynamic property group by with alias
  ebean-core/src/main/java/io/ebeaninternal/server/deploy/DynamicPropertyAggregationFormula.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/STreeProperty.java
  ebean-core/src/main/java/io/ebeaninternal/server/query/SqlTreeNodeBean.java
  ebean-test/src/test/java/io/ebean/xtest/base/DtoQuery2Test.java
Labels: bug
